package ai.nexusone.repository;
import ai.nexusone.entity.AutonomousEnterpriseValuationIntelligence;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
public interface AutonomousEnterpriseValuationIntelligenceRepository extends JpaRepository<AutonomousEnterpriseValuationIntelligence, Long>, JpaSpecificationExecutor<AutonomousEnterpriseValuationIntelligence> {}
