package ai.nexusone.dto; import jakarta.validation.constraints.*; public record AutonomousEnterpriseStrategicGrowthRequest(
 @NotBlank String title,
 @NotBlank String growthVision,
 @NotBlank String growthStrategy,
 @NotBlank String marketExpansionPlan,
 @NotBlank String customerGrowthStrategy,
 @NotBlank String productPortfolioGrowth,
 @NotBlank String digitalGrowthTransformation,
 @NotBlank String partnerEcosystemGrowth,
 @NotBlank String growthRiskAssessment,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double visionScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double growthStrategyScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double marketExpansionScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double customerGrowthScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double productGrowthScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double digitalGrowthScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double ecosystemGrowthScore,
 @NotNull @DecimalMin("0") @DecimalMax("100") Double executionScore,
 @NotNull ai.nexusone.enums.AutonomousEnterpriseStrategicGrowthPriority priority,
 @NotBlank String createdBy) {}
