package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.*; import ai.nexusone.enums.*; import ai.nexusone.exception.*; import ai.nexusone.repository.*; import ai.nexusone.specification.*;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional
public class AutonomousEnterpriseInvestmentStrategyService {
 private final AutonomousEnterpriseInvestmentStrategyRepository repository;
 public AutonomousEnterpriseInvestmentStrategyService(AutonomousEnterpriseInvestmentStrategyRepository repository) { this.repository=repository; }
 public AutonomousEnterpriseInvestmentStrategyResponse generate(AutonomousEnterpriseInvestmentStrategyRequest r) {
  var e=new AutonomousEnterpriseInvestmentStrategy(); e.setTitle(r.title()); e.setInvestmentStrategyVision(r.investmentStrategyVision()); e.setStrategicInvestmentRoadmap(r.strategicInvestmentRoadmap()); e.setGrowthInvestmentStrategy(r.growthInvestmentStrategy()); e.setInnovationInvestmentStrategy(r.innovationInvestmentStrategy()); e.setTechnologyInvestmentStrategy(r.technologyInvestmentStrategy()); e.setMarketExpansionStrategy(r.marketExpansionStrategy()); e.setRiskDiversificationStrategy(r.riskDiversificationStrategy()); e.setExecutiveInvestmentDecision(r.executiveInvestmentDecision()); e.setStrategicInvestmentScore(r.strategicInvestmentScore()); e.setExpectedGrowthScore(r.expectedGrowthScore()); e.setInnovationPotentialScore(r.innovationPotentialScore()); e.setMarketOpportunityScore(r.marketOpportunityScore()); e.setTechnologyReadinessScore(r.technologyReadinessScore()); e.setRiskDiversificationScore(r.riskDiversificationScore()); e.setInvestmentEfficiencyScore(r.investmentEfficiencyScore()); e.setExecutionConfidenceScore(r.executionConfidenceScore());
  double score=(r.strategicInvestmentScore()+r.expectedGrowthScore()+r.innovationPotentialScore()+r.marketOpportunityScore()+r.technologyReadinessScore()+r.riskDiversificationScore()+r.investmentEfficiencyScore()+r.executionConfidenceScore())/8.0;
  e.setEnterpriseInvestmentStrategyScore(Math.round(score*100.0)/100.0); e.setPriority(r.priority()); e.setCreatedBy(r.createdBy()); e.setStatus(AutonomousEnterpriseInvestmentStrategyStatus.GENERATED); return map(repository.save(e)); }
 @Transactional(readOnly=true) public AutonomousEnterpriseInvestmentStrategyResponse getById(Long id) { return map(find(id)); }
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseInvestmentStrategyResponse> getAll(Pageable p) { return repository.findAll(p).map(this::map); }
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseInvestmentStrategyResponse> search(String k,AutonomousEnterpriseInvestmentStrategyPriority p,AutonomousEnterpriseInvestmentStrategyStatus s,Pageable page) { return repository.findAll(AutonomousEnterpriseInvestmentStrategySpecification.filter(k,p,s),page).map(this::map); }
 private AutonomousEnterpriseInvestmentStrategy find(Long id) { return repository.findById(id).orElseThrow(()->new AutonomousEnterpriseInvestmentStrategyNotFoundException(id)); }
 private AutonomousEnterpriseInvestmentStrategyResponse map(AutonomousEnterpriseInvestmentStrategy e) { return new AutonomousEnterpriseInvestmentStrategyResponse(e.getId(),e.getTitle(),e.getInvestmentStrategyVision(),e.getStrategicInvestmentRoadmap(),e.getGrowthInvestmentStrategy(),e.getInnovationInvestmentStrategy(),e.getTechnologyInvestmentStrategy(),e.getMarketExpansionStrategy(),e.getRiskDiversificationStrategy(),e.getExecutiveInvestmentDecision(),e.getStrategicInvestmentScore(),e.getExpectedGrowthScore(),e.getInnovationPotentialScore(),e.getMarketOpportunityScore(),e.getTechnologyReadinessScore(),e.getRiskDiversificationScore(),e.getInvestmentEfficiencyScore(),e.getExecutionConfidenceScore(),e.getEnterpriseInvestmentStrategyScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getCreatedAt(),e.getUpdatedAt()); }
}
