package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.math.*;import java.util.*;import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseAutonomousInnovationService {
 private final AutonomousEnterpriseAutonomousInnovationRepository r;
 public AutonomousEnterpriseAutonomousInnovationService(AutonomousEnterpriseAutonomousInnovationRepository r){this.r=r;}
 public AutonomousEnterpriseAutonomousInnovationResponse generate(AutonomousEnterpriseAutonomousInnovationRequest q){var e=new AutonomousEnterpriseAutonomousInnovation();apply(e,q);e.setStatus(AutonomousEnterpriseAutonomousInnovationStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseAutonomousInnovationResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseAutonomousInnovationResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseAutonomousInnovationResponse> search(String k,AutonomousEnterpriseAutonomousInnovationPriority p,AutonomousEnterpriseAutonomousInnovationStatus s,Pageable page){return r.findAll(AutonomousEnterpriseAutonomousInnovationSpecification.filter(k,p,s),page).map(this::map);}
 public AutonomousEnterpriseAutonomousInnovationResponse review(Long id,AutonomousEnterpriseAutonomousInnovationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseAutonomousInnovationStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseAutonomousInnovationStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseAutonomousInnovationResponse approve(Long id,AutonomousEnterpriseAutonomousInnovationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseAutonomousInnovationStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseAutonomousInnovationStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseAutonomousInnovationResponse reject(Long id,AutonomousEnterpriseAutonomousInnovationActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseAutonomousInnovationStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseAutonomousInnovationStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseAutonomousInnovationStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseAutonomousInnovationResponse publish(Long id,AutonomousEnterpriseAutonomousInnovationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseAutonomousInnovationStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseAutonomousInnovationStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseAutonomousInnovationAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseAutonomousInnovationAnalyticsResponse(a.size(),count(a,AutonomousEnterpriseAutonomousInnovationStatus.GENERATED),count(a,AutonomousEnterpriseAutonomousInnovationStatus.REVIEWED),count(a,AutonomousEnterpriseAutonomousInnovationStatus.APPROVED),count(a,AutonomousEnterpriseAutonomousInnovationStatus.REJECTED),count(a,AutonomousEnterpriseAutonomousInnovationStatus.PUBLISHED),avg(a,AutonomousEnterpriseAutonomousInnovation::getInnovationPotentialScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getMarketOpportunityScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getTechnologyFeasibilityScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getRevenuePotentialScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getBusinessModelScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getCustomerValueScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getRiskReadinessScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getExecutionReadinessScore),avg(a,AutonomousEnterpriseAutonomousInnovation::getAutonomousInnovationScore));}
 private long count(List<AutonomousEnterpriseAutonomousInnovation>a,AutonomousEnterpriseAutonomousInnovationStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseAutonomousInnovation>a,ToDoubleFunction<AutonomousEnterpriseAutonomousInnovation> f){return round(a.stream().mapToDouble(x->{Double v=f.applyAsDouble(x);return v==null?0:v;}).average().orElse(0));}
 private double round(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP).doubleValue();}
 private void require(AutonomousEnterpriseAutonomousInnovation e,AutonomousEnterpriseAutonomousInnovationStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseAutonomousInnovation find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseAutonomousInnovationNotFoundException(id));}
 private void apply(AutonomousEnterpriseAutonomousInnovation e,AutonomousEnterpriseAutonomousInnovationRequest q){e.setTitle(q.title());e.setInnovationOpportunity(q.innovationOpportunity());e.setMarketDisruptionStrategy(q.marketDisruptionStrategy());e.setNewRevenueStrategy(q.newRevenueStrategy());e.setTechnologyInnovationStrategy(q.technologyInnovationStrategy());e.setBusinessModelInnovation(q.businessModelInnovation());e.setCustomerExperienceInnovation(q.customerExperienceInnovation());e.setInnovationRiskAssessment(q.innovationRiskAssessment());e.setAutonomousInnovationRecommendations(q.autonomousInnovationRecommendations());e.setInnovationPotentialScore(q.innovationPotentialScore());e.setMarketOpportunityScore(q.marketOpportunityScore());e.setTechnologyFeasibilityScore(q.technologyFeasibilityScore());e.setRevenuePotentialScore(q.revenuePotentialScore());e.setBusinessModelScore(q.businessModelScore());e.setCustomerValueScore(q.customerValueScore());e.setRiskReadinessScore(q.riskReadinessScore());e.setExecutionReadinessScore(q.executionReadinessScore());e.setAutonomousInnovationScore(round((q.innovationPotentialScore()+q.marketOpportunityScore()+q.technologyFeasibilityScore()+q.revenuePotentialScore()+q.businessModelScore()+q.customerValueScore()+q.riskReadinessScore()+q.executionReadinessScore())/8));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());}
 private AutonomousEnterpriseAutonomousInnovationResponse map(AutonomousEnterpriseAutonomousInnovation e){return new AutonomousEnterpriseAutonomousInnovationResponse(e.getId(),e.getTitle(),e.getInnovationOpportunity(),e.getMarketDisruptionStrategy(),e.getNewRevenueStrategy(),e.getTechnologyInnovationStrategy(),e.getBusinessModelInnovation(),e.getCustomerExperienceInnovation(),e.getInnovationRiskAssessment(),e.getAutonomousInnovationRecommendations(),e.getInnovationPotentialScore(),e.getMarketOpportunityScore(),e.getTechnologyFeasibilityScore(),e.getRevenuePotentialScore(),e.getBusinessModelScore(),e.getCustomerValueScore(),e.getRiskReadinessScore(),e.getExecutionReadinessScore(),e.getAutonomousInnovationScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
