package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import java.time.LocalDateTime;import java.util.*;import java.util.function.ToDoubleFunction;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AutonomousEnterpriseSwarmIntelligenceService{private final AutonomousEnterpriseSwarmIntelligenceRepository repo;public AutonomousEnterpriseSwarmIntelligenceService(AutonomousEnterpriseSwarmIntelligenceRepository r){repo=r;}
@Transactional public AutonomousEnterpriseSwarmIntelligenceResponse generate(AutonomousEnterpriseSwarmIntelligenceRequest q){var r=new AutonomousEnterpriseSwarmIntelligenceReport();r.setTitle(q.title()); r.setAgentCoordination(q.agentCoordination()); r.setAgentCoordinationScore(q.agentCoordinationScore());
 r.setTaskDistribution(q.taskDistribution()); r.setTaskDistributionScore(q.taskDistributionScore());
 r.setModelSwarm(q.modelSwarm()); r.setModelSwarmScore(q.modelSwarmScore());
 r.setEmergentBehavior(q.emergentBehavior()); r.setEmergentBehaviorScore(q.emergentBehaviorScore());
 r.setCollectiveProblemSolving(q.collectiveProblemSolving()); r.setCollectiveProblemSolvingScore(q.collectiveProblemSolvingScore());
 r.setResourceOptimization(q.resourceOptimization()); r.setResourceOptimizationScore(q.resourceOptimizationScore());
 r.setCommunicationEfficiency(q.communicationEfficiency()); r.setCommunicationEfficiencyScore(q.communicationEfficiencyScore());
 r.setResilience(q.resilience()); r.setResilienceScore(q.resilienceScore());
 r.setAutonomousExecution(q.autonomousExecution()); r.setAutonomousExecutionScore(q.autonomousExecutionScore());r.setSwarmRecommendations(q.swarmRecommendations());r.setAutonomousEnterpriseSwarmIntelligenceScore(round(q.agentCoordinationScore()*0.15 + q.taskDistributionScore()*0.13 + q.modelSwarmScore()*0.12 + q.emergentBehaviorScore()*0.11 + q.collectiveProblemSolvingScore()*0.11 + q.resourceOptimizationScore()*0.10 + q.communicationEfficiencyScore()*0.10 + q.resilienceScore()*0.10 + q.autonomousExecutionScore()*0.08));r.setPriority(q.priority());r.setStatus(AutonomousEnterpriseSwarmIntelligenceStatus.GENERATED);r.setCreatedBy(q.createdBy());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseSwarmIntelligenceResponse get(Long id){return map(find(id));} @Transactional(readOnly=true) public Page<AutonomousEnterpriseSwarmIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
@Transactional(readOnly=true) public Page<AutonomousEnterpriseSwarmIntelligenceResponse> search(String k,AutonomousEnterpriseSwarmIntelligencePriority p,AutonomousEnterpriseSwarmIntelligenceStatus s,Pageable x){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrAgentCoordinationContainingIgnoreCaseOrSwarmRecommendationsContainingIgnoreCase(k,k,k,x).map(this::map);if(p!=null)return repo.findByPriority(p,x).map(this::map);if(s!=null)return repo.findByStatus(s,x).map(this::map);return history(x);}
@Transactional public AutonomousEnterpriseSwarmIntelligenceResponse review(Long id,AutonomousEnterpriseSwarmIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSwarmIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");r.setStatus(AutonomousEnterpriseSwarmIntelligenceStatus.REVIEWED);r.setReviewedBy(q.actionBy());r.setReviewedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSwarmIntelligenceResponse approve(Long id,AutonomousEnterpriseSwarmIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSwarmIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");r.setStatus(AutonomousEnterpriseSwarmIntelligenceStatus.APPROVED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSwarmIntelligenceResponse reject(Long id,AutonomousEnterpriseSwarmIntelligenceActionRequest q){var r=find(id);if(r.getStatus()!=AutonomousEnterpriseSwarmIntelligenceStatus.GENERATED&&r.getStatus()!=AutonomousEnterpriseSwarmIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");r.setStatus(AutonomousEnterpriseSwarmIntelligenceStatus.REJECTED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSwarmIntelligenceResponse publish(Long id,AutonomousEnterpriseSwarmIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSwarmIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");r.setStatus(AutonomousEnterpriseSwarmIntelligenceStatus.PUBLISHED);r.setPublishedBy(q.actionBy());r.setPublishedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseSwarmIntelligenceAnalyticsResponse analytics(){var all=repo.findAll();return new AutonomousEnterpriseSwarmIntelligenceAnalyticsResponse(all.size(),cnt(AutonomousEnterpriseSwarmIntelligenceStatus.GENERATED),cnt(AutonomousEnterpriseSwarmIntelligenceStatus.REVIEWED),cnt(AutonomousEnterpriseSwarmIntelligenceStatus.APPROVED),cnt(AutonomousEnterpriseSwarmIntelligenceStatus.REJECTED),cnt(AutonomousEnterpriseSwarmIntelligenceStatus.PUBLISHED),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getAgentCoordinationScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getTaskDistributionScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getModelSwarmScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getEmergentBehaviorScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getCollectiveProblemSolvingScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getResourceOptimizationScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getCommunicationEfficiencyScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getResilienceScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getAutonomousExecutionScore),av(all,AutonomousEnterpriseSwarmIntelligenceReport::getAutonomousEnterpriseSwarmIntelligenceScore));}
private double av(List<AutonomousEnterpriseSwarmIntelligenceReport>a,ToDoubleFunction<AutonomousEnterpriseSwarmIntelligenceReport>f){return round(a.stream().mapToDouble(f).average().orElse(0));}private long cnt(AutonomousEnterpriseSwarmIntelligenceStatus s){return repo.countByStatus(s);}private double round(double v){return Math.round(v*100.0)/100.0;}private void req(AutonomousEnterpriseSwarmIntelligenceReport r,AutonomousEnterpriseSwarmIntelligenceStatus s,String m){if(r.getStatus()!=s)throw new IllegalArgumentException(m);}private AutonomousEnterpriseSwarmIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new AutonomousEnterpriseSwarmIntelligenceNotFoundException(id));}
private AutonomousEnterpriseSwarmIntelligenceResponse map(AutonomousEnterpriseSwarmIntelligenceReport r){return new AutonomousEnterpriseSwarmIntelligenceResponse(r.getId(),r.getTitle(),r.getAgentCoordination(),r.getTaskDistribution(),r.getModelSwarm(),r.getEmergentBehavior(),r.getCollectiveProblemSolving(),r.getResourceOptimization(),r.getCommunicationEfficiency(),r.getResilience(),r.getAutonomousExecution(),r.getSwarmRecommendations(),r.getAgentCoordinationScore(),r.getTaskDistributionScore(),r.getModelSwarmScore(),r.getEmergentBehaviorScore(),r.getCollectiveProblemSolvingScore(),r.getResourceOptimizationScore(),r.getCommunicationEfficiencyScore(),r.getResilienceScore(),r.getAutonomousExecutionScore(),r.getAutonomousEnterpriseSwarmIntelligenceScore(),r.getPriority(),r.getStatus(),r.getCreatedBy(),r.getReviewedBy(),r.getReviewedAt(),r.getDecidedBy(),r.getDecidedAt(),r.getPublishedBy(),r.getPublishedAt(),r.getCreatedAt(),r.getUpdatedAt());}}
