package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.math.*;import java.util.*;import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseUniversalKnowledgeService {
 private final AutonomousEnterpriseUniversalKnowledgeRepository r;
 public AutonomousEnterpriseUniversalKnowledgeService(AutonomousEnterpriseUniversalKnowledgeRepository r){this.r=r;}
 public AutonomousEnterpriseUniversalKnowledgeResponse generate(AutonomousEnterpriseUniversalKnowledgeRequest q){var e=new AutonomousEnterpriseUniversalKnowledge();apply(e,q);e.setStatus(AutonomousEnterpriseUniversalKnowledgeStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseUniversalKnowledgeResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseUniversalKnowledgeResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseUniversalKnowledgeResponse> search(String k,AutonomousEnterpriseUniversalKnowledgePriority p,AutonomousEnterpriseUniversalKnowledgeStatus s,Pageable page){return r.findAll(AutonomousEnterpriseUniversalKnowledgeSpecification.filter(k,p,s),page).map(this::map);}
 public AutonomousEnterpriseUniversalKnowledgeResponse review(Long id,AutonomousEnterpriseUniversalKnowledgeActionRequest q){var e=find(id);require(e,AutonomousEnterpriseUniversalKnowledgeStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseUniversalKnowledgeStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseUniversalKnowledgeResponse approve(Long id,AutonomousEnterpriseUniversalKnowledgeActionRequest q){var e=find(id);require(e,AutonomousEnterpriseUniversalKnowledgeStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseUniversalKnowledgeStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseUniversalKnowledgeResponse reject(Long id,AutonomousEnterpriseUniversalKnowledgeActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseUniversalKnowledgeStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseUniversalKnowledgeStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseUniversalKnowledgeStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseUniversalKnowledgeResponse publish(Long id,AutonomousEnterpriseUniversalKnowledgeActionRequest q){var e=find(id);require(e,AutonomousEnterpriseUniversalKnowledgeStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseUniversalKnowledgeStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseUniversalKnowledgeAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseUniversalKnowledgeAnalyticsResponse(a.size(),count(a,AutonomousEnterpriseUniversalKnowledgeStatus.GENERATED),count(a,AutonomousEnterpriseUniversalKnowledgeStatus.REVIEWED),count(a,AutonomousEnterpriseUniversalKnowledgeStatus.APPROVED),count(a,AutonomousEnterpriseUniversalKnowledgeStatus.REJECTED),count(a,AutonomousEnterpriseUniversalKnowledgeStatus.PUBLISHED),avg(a,AutonomousEnterpriseUniversalKnowledge::getGraphScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getLinkingScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getMemoryScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getDiscoveryScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getGovernanceScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getQualityScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getReuseScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getLearningScore),avg(a,AutonomousEnterpriseUniversalKnowledge::getUniversalKnowledgeScore));}
 private long count(List<AutonomousEnterpriseUniversalKnowledge>a,AutonomousEnterpriseUniversalKnowledgeStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseUniversalKnowledge>a,ToDoubleFunction<AutonomousEnterpriseUniversalKnowledge> f){return round(a.stream().mapToDouble(x->{Double v=f.applyAsDouble(x);return v==null?0:v;}).average().orElse(0));}
 private double round(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP).doubleValue();}
 private void require(AutonomousEnterpriseUniversalKnowledge e,AutonomousEnterpriseUniversalKnowledgeStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseUniversalKnowledge find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseUniversalKnowledgeNotFoundException(id));}
 private void apply(AutonomousEnterpriseUniversalKnowledge e,AutonomousEnterpriseUniversalKnowledgeRequest q){e.setTitle(q.title());e.setKnowledgeGraphStrategy(q.knowledgeGraphStrategy());e.setCrossFabricKnowledgeLinking(q.crossFabricKnowledgeLinking());e.setOrganizationalMemory(q.organizationalMemory());e.setSemanticDiscovery(q.semanticDiscovery());e.setKnowledgeGovernance(q.knowledgeGovernance());e.setKnowledgeQuality(q.knowledgeQuality());e.setReuseAndLearning(q.reuseAndLearning());e.setUniversalKnowledgeRecommendations(q.universalKnowledgeRecommendations());e.setGraphScore(q.graphScore());e.setLinkingScore(q.linkingScore());e.setMemoryScore(q.memoryScore());e.setDiscoveryScore(q.discoveryScore());e.setGovernanceScore(q.governanceScore());e.setQualityScore(q.qualityScore());e.setReuseScore(q.reuseScore());e.setLearningScore(q.learningScore());e.setUniversalKnowledgeScore(round((q.graphScore()+q.linkingScore()+q.memoryScore()+q.discoveryScore()+q.governanceScore()+q.qualityScore()+q.reuseScore()+q.learningScore())/8));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());}
 private AutonomousEnterpriseUniversalKnowledgeResponse map(AutonomousEnterpriseUniversalKnowledge e){return new AutonomousEnterpriseUniversalKnowledgeResponse(e.getId(),e.getTitle(),e.getKnowledgeGraphStrategy(),e.getCrossFabricKnowledgeLinking(),e.getOrganizationalMemory(),e.getSemanticDiscovery(),e.getKnowledgeGovernance(),e.getKnowledgeQuality(),e.getReuseAndLearning(),e.getUniversalKnowledgeRecommendations(),e.getGraphScore(),e.getLinkingScore(),e.getMemoryScore(),e.getDiscoveryScore(),e.getGovernanceScore(),e.getQualityScore(),e.getReuseScore(),e.getLearningScore(),e.getUniversalKnowledgeScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
