package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.math.*;import java.util.*;import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseQuantumIntelligenceService {
 private final AutonomousEnterpriseQuantumIntelligenceRepository r;
 public AutonomousEnterpriseQuantumIntelligenceService(AutonomousEnterpriseQuantumIntelligenceRepository r){this.r=r;}
 public AutonomousEnterpriseQuantumIntelligenceResponse generate(AutonomousEnterpriseQuantumIntelligenceRequest q){var e=new AutonomousEnterpriseQuantumIntelligence();apply(e,q);e.setStatus(AutonomousEnterpriseQuantumIntelligenceStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseQuantumIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseQuantumIntelligenceResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseQuantumIntelligenceResponse> search(String k,AutonomousEnterpriseQuantumIntelligencePriority p,AutonomousEnterpriseQuantumIntelligenceStatus s,Pageable page){return r.findAll(AutonomousEnterpriseQuantumIntelligenceSpecification.filter(k,p,s),page).map(this::map);}
 public AutonomousEnterpriseQuantumIntelligenceResponse review(Long id,AutonomousEnterpriseQuantumIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseQuantumIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseQuantumIntelligenceStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseQuantumIntelligenceResponse approve(Long id,AutonomousEnterpriseQuantumIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseQuantumIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseQuantumIntelligenceStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseQuantumIntelligenceResponse reject(Long id,AutonomousEnterpriseQuantumIntelligenceActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseQuantumIntelligenceStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseQuantumIntelligenceStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseQuantumIntelligenceStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseQuantumIntelligenceResponse publish(Long id,AutonomousEnterpriseQuantumIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseQuantumIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseQuantumIntelligenceStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseQuantumIntelligenceAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseQuantumIntelligenceAnalyticsResponse(a.size(),count(a,AutonomousEnterpriseQuantumIntelligenceStatus.GENERATED),count(a,AutonomousEnterpriseQuantumIntelligenceStatus.REVIEWED),count(a,AutonomousEnterpriseQuantumIntelligenceStatus.APPROVED),count(a,AutonomousEnterpriseQuantumIntelligenceStatus.REJECTED),count(a,AutonomousEnterpriseQuantumIntelligenceStatus.PUBLISHED),avg(a,AutonomousEnterpriseQuantumIntelligence::getOptimizationScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getSimulationScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getOrchestrationScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getRiskModelingScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getSecurityReadinessScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getDataReadinessScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getUseCaseValueScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getAdoptionReadinessScore),avg(a,AutonomousEnterpriseQuantumIntelligence::getQuantumIntelligenceScore));}
 private long count(List<AutonomousEnterpriseQuantumIntelligence>a,AutonomousEnterpriseQuantumIntelligenceStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseQuantumIntelligence>a,ToDoubleFunction<AutonomousEnterpriseQuantumIntelligence> f){return round(a.stream().mapToDouble(x->{Double v=f.applyAsDouble(x);return v==null?0:v;}).average().orElse(0));}
 private double round(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP).doubleValue();}
 private void require(AutonomousEnterpriseQuantumIntelligence e,AutonomousEnterpriseQuantumIntelligenceStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseQuantumIntelligence find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseQuantumIntelligenceNotFoundException(id));}
 private void apply(AutonomousEnterpriseQuantumIntelligence e,AutonomousEnterpriseQuantumIntelligenceRequest q){e.setTitle(q.title());e.setQuantumOptimizationStrategy(q.quantumOptimizationStrategy());e.setQuantumSimulationModel(q.quantumSimulationModel());e.setHybridQuantumClassicalOrchestration(q.hybridQuantumClassicalOrchestration());e.setQuantumRiskModeling(q.quantumRiskModeling());e.setQuantumSecurityReadiness(q.quantumSecurityReadiness());e.setQuantumDataStrategy(q.quantumDataStrategy());e.setEnterpriseUseCases(q.enterpriseUseCases());e.setQuantumIntelligenceRecommendations(q.quantumIntelligenceRecommendations());e.setOptimizationScore(q.optimizationScore());e.setSimulationScore(q.simulationScore());e.setOrchestrationScore(q.orchestrationScore());e.setRiskModelingScore(q.riskModelingScore());e.setSecurityReadinessScore(q.securityReadinessScore());e.setDataReadinessScore(q.dataReadinessScore());e.setUseCaseValueScore(q.useCaseValueScore());e.setAdoptionReadinessScore(q.adoptionReadinessScore());e.setQuantumIntelligenceScore(round((q.optimizationScore()+q.simulationScore()+q.orchestrationScore()+q.riskModelingScore()+q.securityReadinessScore()+q.dataReadinessScore()+q.useCaseValueScore()+q.adoptionReadinessScore())/8));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());}
 private AutonomousEnterpriseQuantumIntelligenceResponse map(AutonomousEnterpriseQuantumIntelligence e){return new AutonomousEnterpriseQuantumIntelligenceResponse(e.getId(),e.getTitle(),e.getQuantumOptimizationStrategy(),e.getQuantumSimulationModel(),e.getHybridQuantumClassicalOrchestration(),e.getQuantumRiskModeling(),e.getQuantumSecurityReadiness(),e.getQuantumDataStrategy(),e.getEnterpriseUseCases(),e.getQuantumIntelligenceRecommendations(),e.getOptimizationScore(),e.getSimulationScore(),e.getOrchestrationScore(),e.getRiskModelingScore(),e.getSecurityReadinessScore(),e.getDataReadinessScore(),e.getUseCaseValueScore(),e.getAdoptionReadinessScore(),e.getQuantumIntelligenceScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
