package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;
import java.time.LocalDateTime;import java.util.*;import java.util.function.ToDoubleFunction;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class AutonomousEnterpriseMetaIntelligenceService {
 private final AutonomousEnterpriseMetaIntelligenceRepository repo;
 public AutonomousEnterpriseMetaIntelligenceService(AutonomousEnterpriseMetaIntelligenceRepository r){repo=r;}
 @Transactional public AutonomousEnterpriseMetaIntelligenceResponse generate(AutonomousEnterpriseMetaIntelligenceRequest q){
  var r=new AutonomousEnterpriseMetaIntelligenceReport();r.setTitle(q.title());
  r.setIntelligenceAssessment(q.intelligenceAssessment());r.setAssessmentScore(q.assessmentScore());
  r.setIntelligenceOrchestration(q.intelligenceOrchestration());r.setOrchestrationScore(q.orchestrationScore());
  r.setIntelligencePrioritization(q.intelligencePrioritization());r.setPrioritizationScore(q.prioritizationScore());
  r.setIntelligenceGovernance(q.intelligenceGovernance());r.setGovernanceScore(q.governanceScore());
  r.setConflictResolution(q.conflictResolution());r.setConflictResolutionScore(q.conflictResolutionScore());
  r.setIntelligenceOptimization(q.intelligenceOptimization());r.setOptimizationScore(q.optimizationScore());
  r.setTrustManagement(q.trustManagement());r.setTrustScore(q.trustScore());
  r.setPerformanceManagement(q.performanceManagement());r.setPerformanceScore(q.performanceScore());
  r.setMetaRecommendations(q.metaRecommendations());
  r.setAutonomousEnterpriseMetaIntelligenceScore(round(q.assessmentScore()*.15+q.orchestrationScore()*.15+q.prioritizationScore()*.13+q.governanceScore()*.13+q.conflictResolutionScore()*.12+q.optimizationScore()*.11+q.trustScore()*.11+q.performanceScore()*.10));
  r.setPriority(q.priority());r.setStatus(AutonomousEnterpriseMetaIntelligenceStatus.GENERATED);r.setCreatedBy(q.createdBy());return map(repo.save(r));}
 @Transactional(readOnly=true) public AutonomousEnterpriseMetaIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseMetaIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseMetaIntelligenceResponse> search(String k,AutonomousEnterpriseMetaIntelligencePriority p,AutonomousEnterpriseMetaIntelligenceStatus s,Pageable x){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrIntelligenceAssessmentContainingIgnoreCaseOrMetaRecommendationsContainingIgnoreCase(k,k,k,x).map(this::map);if(p!=null)return repo.findByPriority(p,x).map(this::map);if(s!=null)return repo.findByStatus(s,x).map(this::map);return history(x);}
 @Transactional public AutonomousEnterpriseMetaIntelligenceResponse review(Long id,AutonomousEnterpriseMetaIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseMetaIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");r.setStatus(AutonomousEnterpriseMetaIntelligenceStatus.REVIEWED);r.setReviewedBy(q.actionBy());r.setReviewedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseMetaIntelligenceResponse approve(Long id,AutonomousEnterpriseMetaIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseMetaIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");r.setStatus(AutonomousEnterpriseMetaIntelligenceStatus.APPROVED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseMetaIntelligenceResponse reject(Long id,AutonomousEnterpriseMetaIntelligenceActionRequest q){var r=find(id);if(r.getStatus()!=AutonomousEnterpriseMetaIntelligenceStatus.GENERATED&&r.getStatus()!=AutonomousEnterpriseMetaIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");r.setStatus(AutonomousEnterpriseMetaIntelligenceStatus.REJECTED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseMetaIntelligenceResponse publish(Long id,AutonomousEnterpriseMetaIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseMetaIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");r.setStatus(AutonomousEnterpriseMetaIntelligenceStatus.PUBLISHED);r.setPublishedBy(q.actionBy());r.setPublishedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional(readOnly=true) public AutonomousEnterpriseMetaIntelligenceAnalyticsResponse analytics(){var a=repo.findAll();return new AutonomousEnterpriseMetaIntelligenceAnalyticsResponse(a.size(),cnt(AutonomousEnterpriseMetaIntelligenceStatus.GENERATED),cnt(AutonomousEnterpriseMetaIntelligenceStatus.REVIEWED),cnt(AutonomousEnterpriseMetaIntelligenceStatus.APPROVED),cnt(AutonomousEnterpriseMetaIntelligenceStatus.REJECTED),cnt(AutonomousEnterpriseMetaIntelligenceStatus.PUBLISHED),av(a,AutonomousEnterpriseMetaIntelligenceReport::getAssessmentScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getOrchestrationScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getPrioritizationScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getGovernanceScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getConflictResolutionScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getOptimizationScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getTrustScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getPerformanceScore),av(a,AutonomousEnterpriseMetaIntelligenceReport::getAutonomousEnterpriseMetaIntelligenceScore));}
 private double av(List<AutonomousEnterpriseMetaIntelligenceReport>a,ToDoubleFunction<AutonomousEnterpriseMetaIntelligenceReport>f){return round(a.stream().mapToDouble(f).average().orElse(0));}
 private long cnt(AutonomousEnterpriseMetaIntelligenceStatus s){return repo.countByStatus(s);}private double round(double v){return Math.round(v*100.0)/100.0;}
 private void req(AutonomousEnterpriseMetaIntelligenceReport r,AutonomousEnterpriseMetaIntelligenceStatus s,String m){if(r.getStatus()!=s)throw new IllegalArgumentException(m);}
 private AutonomousEnterpriseMetaIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new AutonomousEnterpriseMetaIntelligenceNotFoundException(id));}
 private AutonomousEnterpriseMetaIntelligenceResponse map(AutonomousEnterpriseMetaIntelligenceReport r){return new AutonomousEnterpriseMetaIntelligenceResponse(r.getId(),r.getTitle(),r.getIntelligenceAssessment(),r.getIntelligenceOrchestration(),r.getIntelligencePrioritization(),r.getIntelligenceGovernance(),r.getConflictResolution(),r.getIntelligenceOptimization(),r.getTrustManagement(),r.getPerformanceManagement(),r.getMetaRecommendations(),r.getAssessmentScore(),r.getOrchestrationScore(),r.getPrioritizationScore(),r.getGovernanceScore(),r.getConflictResolutionScore(),r.getOptimizationScore(),r.getTrustScore(),r.getPerformanceScore(),r.getAutonomousEnterpriseMetaIntelligenceScore(),r.getPriority(),r.getStatus(),r.getCreatedBy(),r.getReviewedBy(),r.getReviewedAt(),r.getDecidedBy(),r.getDecidedAt(),r.getPublishedBy(),r.getPublishedAt(),r.getCreatedAt(),r.getUpdatedAt());}
}
