package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.math.BigDecimal;import java.math.RoundingMode;
@Service @Transactional
public class AutonomousEnterpriseOmniIntelligenceService {
 private final AutonomousEnterpriseOmniIntelligenceRepository r;
 public AutonomousEnterpriseOmniIntelligenceService(AutonomousEnterpriseOmniIntelligenceRepository r){this.r=r;}
 public AutonomousEnterpriseOmniIntelligenceResponse generate(AutonomousEnterpriseOmniIntelligenceRequest q){var e=new AutonomousEnterpriseOmniIntelligence();apply(e,q);e.setStatus(AutonomousEnterpriseOmniIntelligenceStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseOmniIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseOmniIntelligenceResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseOmniIntelligenceResponse> search(String k,AutonomousEnterpriseOmniIntelligencePriority p,AutonomousEnterpriseOmniIntelligenceStatus s,Pageable page){return r.findAll(AutonomousEnterpriseOmniIntelligenceSpecification.filter(k,p,s),page).map(this::map);}
 public AutonomousEnterpriseOmniIntelligenceResponse review(Long id,AutonomousEnterpriseOmniIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseOmniIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseOmniIntelligenceStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseOmniIntelligenceResponse approve(Long id,AutonomousEnterpriseOmniIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseOmniIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseOmniIntelligenceStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseOmniIntelligenceResponse reject(Long id,AutonomousEnterpriseOmniIntelligenceActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseOmniIntelligenceStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseOmniIntelligenceStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseOmniIntelligenceStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseOmniIntelligenceResponse publish(Long id,AutonomousEnterpriseOmniIntelligenceActionRequest q){var e=find(id);require(e,AutonomousEnterpriseOmniIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseOmniIntelligenceStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseOmniIntelligenceAnalyticsResponse analytics(){var all=r.findAll();return new AutonomousEnterpriseOmniIntelligenceAnalyticsResponse(all.size(),count(all,AutonomousEnterpriseOmniIntelligenceStatus.GENERATED),count(all,AutonomousEnterpriseOmniIntelligenceStatus.REVIEWED),count(all,AutonomousEnterpriseOmniIntelligenceStatus.APPROVED),count(all,AutonomousEnterpriseOmniIntelligenceStatus.REJECTED),count(all,AutonomousEnterpriseOmniIntelligenceStatus.PUBLISHED),avg(all,"a"),avg(all,"f"),avg(all,"r"),avg(all,"s"),avg(all,"c"),avg(all,"o"),avg(all,"t"),avg(all,"x"),round(all.stream().mapToDouble(x->x.getAutonomousEnterpriseOmniIntelligenceScore()==null?0:x.getAutonomousEnterpriseOmniIntelligenceScore()).average().orElse(0)));}
 private long count(java.util.List<AutonomousEnterpriseOmniIntelligence> a,AutonomousEnterpriseOmniIntelligenceStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(java.util.List<AutonomousEnterpriseOmniIntelligence>a,String k){return round(a.stream().mapToDouble(x->switch(k){case"a"->x.getAssessmentScore();case"f"->x.getFusionScore();case"r"->x.getReasoningScore();case"s"->x.getSynchronizationScore();case"c"->x.getContextScore();case"o"->x.getOrchestrationScore();case"t"->x.getTrustScore();default->x.getOptimizationScore();}).average().orElse(0));}
 private double round(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP).doubleValue();}
 private void require(AutonomousEnterpriseOmniIntelligence e,AutonomousEnterpriseOmniIntelligenceStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseOmniIntelligence find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseOmniIntelligenceNotFoundException(id));}
 private void apply(AutonomousEnterpriseOmniIntelligence e,AutonomousEnterpriseOmniIntelligenceRequest q){e.setTitle(q.title());e.setOmnichannelAssessment(q.omnichannelAssessment());e.setCrossDomainFusion(q.crossDomainFusion());e.setMultimodalReasoning(q.multimodalReasoning());e.setIntelligenceSynchronization(q.intelligenceSynchronization());e.setContextUnification(q.contextUnification());e.setDecisionOrchestration(q.decisionOrchestration());e.setGovernanceAndTrust(q.governanceAndTrust());e.setOutcomeOptimization(q.outcomeOptimization());e.setOmniRecommendations(q.omniRecommendations());e.setAssessmentScore(q.assessmentScore());e.setFusionScore(q.fusionScore());e.setReasoningScore(q.reasoningScore());e.setSynchronizationScore(q.synchronizationScore());e.setContextScore(q.contextScore());e.setOrchestrationScore(q.orchestrationScore());e.setTrustScore(q.trustScore());e.setOptimizationScore(q.optimizationScore());e.setAutonomousEnterpriseOmniIntelligenceScore(round((q.assessmentScore()+q.fusionScore()+q.reasoningScore()+q.synchronizationScore()+q.contextScore()+q.orchestrationScore()+q.trustScore()+q.optimizationScore())/8));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());}
 private AutonomousEnterpriseOmniIntelligenceResponse map(AutonomousEnterpriseOmniIntelligence e){return new AutonomousEnterpriseOmniIntelligenceResponse(e.getId(),e.getTitle(),e.getOmnichannelAssessment(),e.getCrossDomainFusion(),e.getMultimodalReasoning(),e.getIntelligenceSynchronization(),e.getContextUnification(),e.getDecisionOrchestration(),e.getGovernanceAndTrust(),e.getOutcomeOptimization(),e.getOmniRecommendations(),e.getAssessmentScore(),e.getFusionScore(),e.getReasoningScore(),e.getSynchronizationScore(),e.getContextScore(),e.getOrchestrationScore(),e.getTrustScore(),e.getOptimizationScore(),e.getAutonomousEnterpriseOmniIntelligenceScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
