package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import java.time.LocalDateTime;import java.util.*;import java.util.function.ToDoubleFunction;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AutonomousEnterpriseSelfEvolvingIntelligenceService{private final AutonomousEnterpriseSelfEvolvingIntelligenceRepository repo;public AutonomousEnterpriseSelfEvolvingIntelligenceService(AutonomousEnterpriseSelfEvolvingIntelligenceRepository r){repo=r;}
@Transactional public AutonomousEnterpriseSelfEvolvingIntelligenceResponse generate(AutonomousEnterpriseSelfEvolvingIntelligenceRequest q){var r=new AutonomousEnterpriseSelfEvolvingIntelligenceReport();r.setTitle(q.title()); r.setLearningVelocity(q.learningVelocity()); r.setLearningVelocityScore(q.learningVelocityScore());
 r.setAdaptationCapacity(q.adaptationCapacity()); r.setAdaptationCapacityScore(q.adaptationCapacityScore());
 r.setModelEvolution(q.modelEvolution()); r.setModelEvolutionScore(q.modelEvolutionScore());
 r.setKnowledgeExpansion(q.knowledgeExpansion()); r.setKnowledgeExpansionScore(q.knowledgeExpansionScore());
 r.setFeedbackIntegration(q.feedbackIntegration()); r.setFeedbackIntegrationScore(q.feedbackIntegrationScore());
 r.setCapabilityEmergence(q.capabilityEmergence()); r.setCapabilityEmergenceScore(q.capabilityEmergenceScore());
 r.setGovernanceAlignment(q.governanceAlignment()); r.setGovernanceAlignmentScore(q.governanceAlignmentScore());
 r.setSafetyPreservation(q.safetyPreservation()); r.setSafetyPreservationScore(q.safetyPreservationScore());
 r.setOutcomeImprovement(q.outcomeImprovement()); r.setOutcomeImprovementScore(q.outcomeImprovementScore());r.setEvolutionRecommendations(q.evolutionRecommendations());r.setAutonomousEnterpriseSelfEvolvingIntelligenceScore(round(q.learningVelocityScore()*0.15 + q.adaptationCapacityScore()*0.13 + q.modelEvolutionScore()*0.12 + q.knowledgeExpansionScore()*0.11 + q.feedbackIntegrationScore()*0.11 + q.capabilityEmergenceScore()*0.10 + q.governanceAlignmentScore()*0.10 + q.safetyPreservationScore()*0.10 + q.outcomeImprovementScore()*0.08));r.setPriority(q.priority());r.setStatus(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.GENERATED);r.setCreatedBy(q.createdBy());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseSelfEvolvingIntelligenceResponse get(Long id){return map(find(id));} @Transactional(readOnly=true) public Page<AutonomousEnterpriseSelfEvolvingIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
@Transactional(readOnly=true) public Page<AutonomousEnterpriseSelfEvolvingIntelligenceResponse> search(String k,AutonomousEnterpriseSelfEvolvingIntelligencePriority p,AutonomousEnterpriseSelfEvolvingIntelligenceStatus s,Pageable x){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrLearningVelocityContainingIgnoreCaseOrEvolutionRecommendationsContainingIgnoreCase(k,k,k,x).map(this::map);if(p!=null)return repo.findByPriority(p,x).map(this::map);if(s!=null)return repo.findByStatus(s,x).map(this::map);return history(x);}
@Transactional public AutonomousEnterpriseSelfEvolvingIntelligenceResponse review(Long id,AutonomousEnterpriseSelfEvolvingIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSelfEvolvingIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");r.setStatus(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REVIEWED);r.setReviewedBy(q.actionBy());r.setReviewedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSelfEvolvingIntelligenceResponse approve(Long id,AutonomousEnterpriseSelfEvolvingIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");r.setStatus(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.APPROVED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSelfEvolvingIntelligenceResponse reject(Long id,AutonomousEnterpriseSelfEvolvingIntelligenceActionRequest q){var r=find(id);if(r.getStatus()!=AutonomousEnterpriseSelfEvolvingIntelligenceStatus.GENERATED&&r.getStatus()!=AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");r.setStatus(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REJECTED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseSelfEvolvingIntelligenceResponse publish(Long id,AutonomousEnterpriseSelfEvolvingIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseSelfEvolvingIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");r.setStatus(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.PUBLISHED);r.setPublishedBy(q.actionBy());r.setPublishedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseSelfEvolvingIntelligenceAnalyticsResponse analytics(){var all=repo.findAll();return new AutonomousEnterpriseSelfEvolvingIntelligenceAnalyticsResponse(all.size(),cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.GENERATED),cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REVIEWED),cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.APPROVED),cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.REJECTED),cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus.PUBLISHED),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getLearningVelocityScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getAdaptationCapacityScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getModelEvolutionScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getKnowledgeExpansionScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getFeedbackIntegrationScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getCapabilityEmergenceScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getGovernanceAlignmentScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getSafetyPreservationScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getOutcomeImprovementScore),av(all,AutonomousEnterpriseSelfEvolvingIntelligenceReport::getAutonomousEnterpriseSelfEvolvingIntelligenceScore));}
private double av(List<AutonomousEnterpriseSelfEvolvingIntelligenceReport>a,ToDoubleFunction<AutonomousEnterpriseSelfEvolvingIntelligenceReport>f){return round(a.stream().mapToDouble(f).average().orElse(0));}private long cnt(AutonomousEnterpriseSelfEvolvingIntelligenceStatus s){return repo.countByStatus(s);}private double round(double v){return Math.round(v*100.0)/100.0;}private void req(AutonomousEnterpriseSelfEvolvingIntelligenceReport r,AutonomousEnterpriseSelfEvolvingIntelligenceStatus s,String m){if(r.getStatus()!=s)throw new IllegalArgumentException(m);}private AutonomousEnterpriseSelfEvolvingIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new AutonomousEnterpriseSelfEvolvingIntelligenceNotFoundException(id));}
private AutonomousEnterpriseSelfEvolvingIntelligenceResponse map(AutonomousEnterpriseSelfEvolvingIntelligenceReport r){return new AutonomousEnterpriseSelfEvolvingIntelligenceResponse(r.getId(),r.getTitle(),r.getLearningVelocity(),r.getAdaptationCapacity(),r.getModelEvolution(),r.getKnowledgeExpansion(),r.getFeedbackIntegration(),r.getCapabilityEmergence(),r.getGovernanceAlignment(),r.getSafetyPreservation(),r.getOutcomeImprovement(),r.getEvolutionRecommendations(),r.getLearningVelocityScore(),r.getAdaptationCapacityScore(),r.getModelEvolutionScore(),r.getKnowledgeExpansionScore(),r.getFeedbackIntegrationScore(),r.getCapabilityEmergenceScore(),r.getGovernanceAlignmentScore(),r.getSafetyPreservationScore(),r.getOutcomeImprovementScore(),r.getAutonomousEnterpriseSelfEvolvingIntelligenceScore(),r.getPriority(),r.getStatus(),r.getCreatedBy(),r.getReviewedBy(),r.getReviewedAt(),r.getDecidedBy(),r.getDecidedAt(),r.getPublishedBy(),r.getPublishedAt(),r.getCreatedAt(),r.getUpdatedAt());}}
