package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.*; import ai.nexusone.enums.*; import ai.nexusone.exception.*; import ai.nexusone.repository.*; import java.time.LocalDateTime; import java.util.*; import java.util.function.ToDoubleFunction; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AutonomousEnterpriseReasoningService{private final AutonomousEnterpriseReasoningRepository repo; public AutonomousEnterpriseReasoningService(AutonomousEnterpriseReasoningRepository r){repo=r;}
@Transactional public AutonomousEnterpriseReasoningResponse generate(AutonomousEnterpriseReasoningRequest q){var r=new AutonomousEnterpriseReasoningReport();r.setTitle(q.title()); r.setCausalReasoning(q.causalReasoning()); r.setCausalReasoningScore(q.causalReasoningScore());
 r.setMultiStepReasoning(q.multiStepReasoning()); r.setMultiStepReasoningScore(q.multiStepReasoningScore());
 r.setStrategicReasoning(q.strategicReasoning()); r.setStrategicReasoningScore(q.strategicReasoningScore());
 r.setOperationalReasoning(q.operationalReasoning()); r.setOperationalReasoningScore(q.operationalReasoningScore());
 r.setPredictiveReasoning(q.predictiveReasoning()); r.setPredictiveReasoningScore(q.predictiveReasoningScore());
 r.setDecisionJustification(q.decisionJustification()); r.setDecisionJustificationScore(q.decisionJustificationScore());
 r.setAdaptiveReasoning(q.adaptiveReasoning()); r.setAdaptiveReasoningScore(q.adaptiveReasoningScore());
 r.setGoalDrivenReasoning(q.goalDrivenReasoning()); r.setGoalDrivenReasoningScore(q.goalDrivenReasoningScore());
 r.setEnterpriseKnowledgeReasoning(q.enterpriseKnowledgeReasoning()); r.setEnterpriseKnowledgeReasoningScore(q.enterpriseKnowledgeReasoningScore());r.setReasoningRecommendations(q.reasoningRecommendations());r.setAutonomousEnterpriseReasoningScore(round(q.causalReasoningScore()*0.15+q.multiStepReasoningScore()*0.13+q.strategicReasoningScore()*0.13+q.operationalReasoningScore()*0.11+q.predictiveReasoningScore()*0.11+q.decisionJustificationScore()*0.1+q.adaptiveReasoningScore()*0.1+q.goalDrivenReasoningScore()*0.09+q.enterpriseKnowledgeReasoningScore()*0.08));r.setPriority(q.priority());r.setStatus(AutonomousEnterpriseReasoningStatus.GENERATED);r.setCreatedBy(q.createdBy());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseReasoningResponse get(Long id){return map(find(id));} @Transactional(readOnly=true) public Page<AutonomousEnterpriseReasoningResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
@Transactional(readOnly=true) public Page<AutonomousEnterpriseReasoningResponse> search(String k,AutonomousEnterpriseReasoningPriority p,AutonomousEnterpriseReasoningStatus s,Pageable pg){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrCausalReasoningContainingIgnoreCaseOrReasoningRecommendationsContainingIgnoreCase(k,k,k,pg).map(this::map);if(p!=null)return repo.findByPriority(p,pg).map(this::map);if(s!=null)return repo.findByStatus(s,pg).map(this::map);return history(pg);}
@Transactional public AutonomousEnterpriseReasoningResponse review(Long id,AutonomousEnterpriseReasoningActionRequest q){var r=find(id);req(r,AutonomousEnterpriseReasoningStatus.GENERATED,"Only GENERATED reports can be reviewed");r.setStatus(AutonomousEnterpriseReasoningStatus.REVIEWED);r.setReviewedBy(q.actionBy());r.setReviewedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseReasoningResponse approve(Long id,AutonomousEnterpriseReasoningActionRequest q){var r=find(id);req(r,AutonomousEnterpriseReasoningStatus.REVIEWED,"Only REVIEWED reports can be approved");r.setStatus(AutonomousEnterpriseReasoningStatus.APPROVED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseReasoningResponse reject(Long id,AutonomousEnterpriseReasoningActionRequest q){var r=find(id);if(r.getStatus()!=AutonomousEnterpriseReasoningStatus.GENERATED&&r.getStatus()!=AutonomousEnterpriseReasoningStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");r.setStatus(AutonomousEnterpriseReasoningStatus.REJECTED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional public AutonomousEnterpriseReasoningResponse publish(Long id,AutonomousEnterpriseReasoningActionRequest q){var r=find(id);req(r,AutonomousEnterpriseReasoningStatus.APPROVED,"Only APPROVED reports can be published");r.setStatus(AutonomousEnterpriseReasoningStatus.PUBLISHED);r.setPublishedBy(q.actionBy());r.setPublishedAt(LocalDateTime.now());return map(repo.save(r));}
@Transactional(readOnly=true) public AutonomousEnterpriseReasoningAnalyticsResponse analytics(){var all=repo.findAll();return new AutonomousEnterpriseReasoningAnalyticsResponse(all.size(),cnt(AutonomousEnterpriseReasoningStatus.GENERATED),cnt(AutonomousEnterpriseReasoningStatus.REVIEWED),cnt(AutonomousEnterpriseReasoningStatus.APPROVED),cnt(AutonomousEnterpriseReasoningStatus.REJECTED),cnt(AutonomousEnterpriseReasoningStatus.PUBLISHED),avg(all,AutonomousEnterpriseReasoningReport::getCausalReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getMultiStepReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getStrategicReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getOperationalReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getPredictiveReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getDecisionJustificationScore),avg(all,AutonomousEnterpriseReasoningReport::getAdaptiveReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getGoalDrivenReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getEnterpriseKnowledgeReasoningScore),avg(all,AutonomousEnterpriseReasoningReport::getAutonomousEnterpriseReasoningScore));}
private long cnt(AutonomousEnterpriseReasoningStatus s){return repo.countByStatus(s);} private double avg(List<AutonomousEnterpriseReasoningReport>a,ToDoubleFunction<AutonomousEnterpriseReasoningReport>x){return round(a.stream().mapToDouble(x).average().orElse(0));} private double round(double v){return Math.round(v*100.0)/100.0;} private void req(AutonomousEnterpriseReasoningReport r,AutonomousEnterpriseReasoningStatus s,String m){if(r.getStatus()!=s)throw new IllegalArgumentException(m);} private AutonomousEnterpriseReasoningReport find(Long id){return repo.findById(id).orElseThrow(()->new AutonomousEnterpriseReasoningNotFoundException(id));}
private AutonomousEnterpriseReasoningResponse map(AutonomousEnterpriseReasoningReport r){return new AutonomousEnterpriseReasoningResponse(r.getId(),r.getTitle(),r.getCausalReasoning(),r.getMultiStepReasoning(),r.getStrategicReasoning(),r.getOperationalReasoning(),r.getPredictiveReasoning(),r.getDecisionJustification(),r.getAdaptiveReasoning(),r.getGoalDrivenReasoning(),r.getEnterpriseKnowledgeReasoning(),r.getReasoningRecommendations(),r.getCausalReasoningScore(),r.getMultiStepReasoningScore(),r.getStrategicReasoningScore(),r.getOperationalReasoningScore(),r.getPredictiveReasoningScore(),r.getDecisionJustificationScore(),r.getAdaptiveReasoningScore(),r.getGoalDrivenReasoningScore(),r.getEnterpriseKnowledgeReasoningScore(),r.getAutonomousEnterpriseReasoningScore(),r.getPriority(),r.getStatus(),r.getCreatedBy(),r.getReviewedBy(),r.getReviewedAt(),r.getDecidedBy(),r.getDecidedAt(),r.getPublishedBy(),r.getPublishedAt(),r.getCreatedAt(),r.getUpdatedAt());}
}
