package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;
import java.time.LocalDateTime;import java.util.*;import java.util.function.ToDoubleFunction;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class AutonomousEnterpriseCollectiveIntelligenceService {
 private final AutonomousEnterpriseCollectiveIntelligenceRepository repo;
 public AutonomousEnterpriseCollectiveIntelligenceService(AutonomousEnterpriseCollectiveIntelligenceRepository r){repo=r;}
 @Transactional public AutonomousEnterpriseCollectiveIntelligenceResponse generate(AutonomousEnterpriseCollectiveIntelligenceRequest q){
  var r=new AutonomousEnterpriseCollectiveIntelligenceReport(); r.setTitle(q.title());r.setHumanExpertise(q.humanExpertise());r.setHumanExpertiseScore(q.humanExpertiseScore());r.setAgentCollaboration(q.agentCollaboration());r.setAgentCollaborationScore(q.agentCollaborationScore());r.setCrossTeamKnowledge(q.crossTeamKnowledge());r.setCrossTeamKnowledgeScore(q.crossTeamKnowledgeScore());r.setConsensusQuality(q.consensusQuality());r.setConsensusQualityScore(q.consensusQualityScore());r.setDiversityOfThought(q.diversityOfThought());r.setDiversityOfThoughtScore(q.diversityOfThoughtScore());r.setSharedLearning(q.sharedLearning());r.setSharedLearningScore(q.sharedLearningScore());r.setDecisionAlignment(q.decisionAlignment());r.setDecisionAlignmentScore(q.decisionAlignmentScore());r.setGovernanceAlignment(q.governanceAlignment());r.setGovernanceAlignmentScore(q.governanceAlignmentScore());r.setOutcomeImpact(q.outcomeImpact());r.setOutcomeImpactScore(q.outcomeImpactScore());r.setCollectiveRecommendations(q.collectiveRecommendations());
  r.setAutonomousEnterpriseCollectiveIntelligenceScore(round(q.humanExpertiseScore()*.14+q.agentCollaborationScore()*.14+q.crossTeamKnowledgeScore()*.12+q.consensusQualityScore()*.12+q.diversityOfThoughtScore()*.10+q.sharedLearningScore()*.10+q.decisionAlignmentScore()*.10+q.governanceAlignmentScore()*.10+q.outcomeImpactScore()*.08));
  r.setPriority(q.priority());r.setStatus(AutonomousEnterpriseCollectiveIntelligenceStatus.GENERATED);r.setCreatedBy(q.createdBy());return map(repo.save(r));
 }
 @Transactional(readOnly=true) public AutonomousEnterpriseCollectiveIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseCollectiveIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseCollectiveIntelligenceResponse> search(String k,AutonomousEnterpriseCollectiveIntelligencePriority p,AutonomousEnterpriseCollectiveIntelligenceStatus s,Pageable x){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrHumanExpertiseContainingIgnoreCaseOrCollectiveRecommendationsContainingIgnoreCase(k,k,k,x).map(this::map);if(p!=null)return repo.findByPriority(p,x).map(this::map);if(s!=null)return repo.findByStatus(s,x).map(this::map);return history(x);}
 @Transactional public AutonomousEnterpriseCollectiveIntelligenceResponse review(Long id,AutonomousEnterpriseCollectiveIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseCollectiveIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");r.setStatus(AutonomousEnterpriseCollectiveIntelligenceStatus.REVIEWED);r.setReviewedBy(q.actionBy());r.setReviewedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseCollectiveIntelligenceResponse approve(Long id,AutonomousEnterpriseCollectiveIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseCollectiveIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");r.setStatus(AutonomousEnterpriseCollectiveIntelligenceStatus.APPROVED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseCollectiveIntelligenceResponse reject(Long id,AutonomousEnterpriseCollectiveIntelligenceActionRequest q){var r=find(id);if(r.getStatus()!=AutonomousEnterpriseCollectiveIntelligenceStatus.GENERATED&&r.getStatus()!=AutonomousEnterpriseCollectiveIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");r.setStatus(AutonomousEnterpriseCollectiveIntelligenceStatus.REJECTED);r.setDecidedBy(q.actionBy());r.setDecidedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional public AutonomousEnterpriseCollectiveIntelligenceResponse publish(Long id,AutonomousEnterpriseCollectiveIntelligenceActionRequest q){var r=find(id);req(r,AutonomousEnterpriseCollectiveIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");r.setStatus(AutonomousEnterpriseCollectiveIntelligenceStatus.PUBLISHED);r.setPublishedBy(q.actionBy());r.setPublishedAt(LocalDateTime.now());return map(repo.save(r));}
 @Transactional(readOnly=true) public AutonomousEnterpriseCollectiveIntelligenceAnalyticsResponse analytics(){var a=repo.findAll();return new AutonomousEnterpriseCollectiveIntelligenceAnalyticsResponse(a.size(),cnt(AutonomousEnterpriseCollectiveIntelligenceStatus.GENERATED),cnt(AutonomousEnterpriseCollectiveIntelligenceStatus.REVIEWED),cnt(AutonomousEnterpriseCollectiveIntelligenceStatus.APPROVED),cnt(AutonomousEnterpriseCollectiveIntelligenceStatus.REJECTED),cnt(AutonomousEnterpriseCollectiveIntelligenceStatus.PUBLISHED),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getHumanExpertiseScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getAgentCollaborationScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getCrossTeamKnowledgeScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getConsensusQualityScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getDiversityOfThoughtScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getSharedLearningScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getDecisionAlignmentScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getGovernanceAlignmentScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getOutcomeImpactScore),av(a,AutonomousEnterpriseCollectiveIntelligenceReport::getAutonomousEnterpriseCollectiveIntelligenceScore));}
 private double av(List<AutonomousEnterpriseCollectiveIntelligenceReport>a,ToDoubleFunction<AutonomousEnterpriseCollectiveIntelligenceReport>f){return round(a.stream().mapToDouble(f).average().orElse(0));} private long cnt(AutonomousEnterpriseCollectiveIntelligenceStatus s){return repo.countByStatus(s);} private double round(double v){return Math.round(v*100.0)/100.0;}
 private void req(AutonomousEnterpriseCollectiveIntelligenceReport r,AutonomousEnterpriseCollectiveIntelligenceStatus s,String m){if(r.getStatus()!=s)throw new IllegalArgumentException(m);} private AutonomousEnterpriseCollectiveIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new AutonomousEnterpriseCollectiveIntelligenceNotFoundException(id));}
 private AutonomousEnterpriseCollectiveIntelligenceResponse map(AutonomousEnterpriseCollectiveIntelligenceReport r){return new AutonomousEnterpriseCollectiveIntelligenceResponse(r.getId(),r.getTitle(),r.getHumanExpertise(),r.getAgentCollaboration(),r.getCrossTeamKnowledge(),r.getConsensusQuality(),r.getDiversityOfThought(),r.getSharedLearning(),r.getDecisionAlignment(),r.getGovernanceAlignment(),r.getOutcomeImpact(),r.getCollectiveRecommendations(),r.getHumanExpertiseScore(),r.getAgentCollaborationScore(),r.getCrossTeamKnowledgeScore(),r.getConsensusQualityScore(),r.getDiversityOfThoughtScore(),r.getSharedLearningScore(),r.getDecisionAlignmentScore(),r.getGovernanceAlignmentScore(),r.getOutcomeImpactScore(),r.getAutonomousEnterpriseCollectiveIntelligenceScore(),r.getPriority(),r.getStatus(),r.getCreatedBy(),r.getReviewedBy(),r.getReviewedAt(),r.getDecidedBy(),r.getDecidedAt(),r.getPublishedBy(),r.getPublishedAt(),r.getCreatedAt(),r.getUpdatedAt());}
}
