package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.*; import ai.nexusone.enums.*; import ai.nexusone.exception.*; import ai.nexusone.repository.*; import ai.nexusone.specification.*;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*; import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseSustainabilityService {
 private final AutonomousEnterpriseSustainabilityRepository r;
 public AutonomousEnterpriseSustainabilityService(AutonomousEnterpriseSustainabilityRepository r){this.r=r;}
 public AutonomousEnterpriseSustainabilityResponse generate(AutonomousEnterpriseSustainabilityRequest q){var e=new AutonomousEnterpriseSustainability();e.setTitle(q.title());e.setSustainabilityVision(q.sustainabilityVision());e.setEsgStrategy(q.esgStrategy());e.setCarbonReductionPlan(q.carbonReductionPlan());e.setEnergyEfficiencyProgram(q.energyEfficiencyProgram());e.setCircularEconomyStrategy(q.circularEconomyStrategy());e.setSustainableSupplyChain(q.sustainableSupplyChain());e.setClimateRiskAssessment(q.climateRiskAssessment());e.setRegulatoryCompliancePlan(q.regulatoryCompliancePlan());e.setVisionScore(q.visionScore());e.setEsgScore(q.esgScore());e.setCarbonReductionScore(q.carbonReductionScore());e.setEnergyEfficiencyScore(q.energyEfficiencyScore());e.setCircularEconomyScore(q.circularEconomyScore());e.setSupplyChainScore(q.supplyChainScore());e.setClimateRiskScore(q.climateRiskScore());e.setComplianceScore(q.complianceScore());e.setSustainabilityScore(Math.round((q.visionScore()+q.esgScore()+q.carbonReductionScore()+q.energyEfficiencyScore()+q.circularEconomyScore()+q.supplyChainScore()+q.climateRiskScore()+q.complianceScore())/8.0*100.0)/100.0);e.setPriority(q.priority());e.setCreatedBy(q.createdBy());e.setStatus(AutonomousEnterpriseSustainabilityStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseSustainabilityResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseSustainabilityResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseSustainabilityResponse> search(String k,AutonomousEnterpriseSustainabilityPriority p,AutonomousEnterpriseSustainabilityStatus s,Pageable pg){return r.findAll(AutonomousEnterpriseSustainabilitySpecification.filter(k,p,s),pg).map(this::map);}
 public AutonomousEnterpriseSustainabilityResponse review(Long id,AutonomousEnterpriseSustainabilityActionRequest q){var e=find(id);need(e,AutonomousEnterpriseSustainabilityStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseSustainabilityStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseSustainabilityResponse approve(Long id,AutonomousEnterpriseSustainabilityActionRequest q){var e=find(id);need(e,AutonomousEnterpriseSustainabilityStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseSustainabilityStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseSustainabilityResponse reject(Long id,AutonomousEnterpriseSustainabilityActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseSustainabilityStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseSustainabilityStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseSustainabilityStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseSustainabilityResponse publish(Long id,AutonomousEnterpriseSustainabilityActionRequest q){var e=find(id);need(e,AutonomousEnterpriseSustainabilityStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseSustainabilityStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseSustainabilityAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseSustainabilityAnalyticsResponse(a.size(),cnt(a,AutonomousEnterpriseSustainabilityStatus.GENERATED),cnt(a,AutonomousEnterpriseSustainabilityStatus.REVIEWED),cnt(a,AutonomousEnterpriseSustainabilityStatus.APPROVED),cnt(a,AutonomousEnterpriseSustainabilityStatus.REJECTED),cnt(a,AutonomousEnterpriseSustainabilityStatus.PUBLISHED),avg(a,AutonomousEnterpriseSustainability::getVisionScore),avg(a,AutonomousEnterpriseSustainability::getEsgScore),avg(a,AutonomousEnterpriseSustainability::getCarbonReductionScore),avg(a,AutonomousEnterpriseSustainability::getEnergyEfficiencyScore),avg(a,AutonomousEnterpriseSustainability::getCircularEconomyScore),avg(a,AutonomousEnterpriseSustainability::getSupplyChainScore),avg(a,AutonomousEnterpriseSustainability::getClimateRiskScore),avg(a,AutonomousEnterpriseSustainability::getComplianceScore),avg(a,AutonomousEnterpriseSustainability::getSustainabilityScore));}
 private long cnt(List<AutonomousEnterpriseSustainability> a,AutonomousEnterpriseSustainabilityStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseSustainability> a,ToDoubleFunction<AutonomousEnterpriseSustainability> f){return Math.round(a.stream().mapToDouble(f).average().orElse(0)*100.0)/100.0;}
 private AutonomousEnterpriseSustainability find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseSustainabilityNotFoundException(id));}
 private void need(AutonomousEnterpriseSustainability e,AutonomousEnterpriseSustainabilityStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseSustainabilityResponse map(AutonomousEnterpriseSustainability e){return new AutonomousEnterpriseSustainabilityResponse(e.getId(),e.getTitle(),e.getSustainabilityVision(),e.getEsgStrategy(),e.getCarbonReductionPlan(),e.getEnergyEfficiencyProgram(),e.getCircularEconomyStrategy(),e.getSustainableSupplyChain(),e.getClimateRiskAssessment(),e.getRegulatoryCompliancePlan(),e.getVisionScore(),e.getEsgScore(),e.getCarbonReductionScore(),e.getEnergyEfficiencyScore(),e.getCircularEconomyScore(),e.getSupplyChainScore(),e.getClimateRiskScore(),e.getComplianceScore(),e.getSustainabilityScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
