package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.*;import java.util.*;import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseResilienceService {
 private final AutonomousEnterpriseResilienceRepository r;
 public AutonomousEnterpriseResilienceService(AutonomousEnterpriseResilienceRepository r){this.r=r;}
 public AutonomousEnterpriseResilienceResponse generate(AutonomousEnterpriseResilienceRequest q){var e=new AutonomousEnterpriseResilience();e.setTitle(q.title());e.setResilienceVision(q.resilienceVision());e.setBusinessContinuityPlan(q.businessContinuityPlan());e.setDisasterRecoveryStrategy(q.disasterRecoveryStrategy());e.setCyberResilienceFramework(q.cyberResilienceFramework());e.setInfrastructureResilienceModel(q.infrastructureResilienceModel());e.setWorkforceResilienceProgram(q.workforceResilienceProgram());e.setThirdPartyResilienceAssessment(q.thirdPartyResilienceAssessment());e.setSupplyChainResilienceStrategy(q.supplyChainResilienceStrategy());e.setOperationalResilienceBlueprint(q.operationalResilienceBlueprint());e.setVisionScore(q.visionScore());e.setContinuityScore(q.continuityScore());e.setRecoveryScore(q.recoveryScore());e.setCyberScore(q.cyberScore());e.setInfrastructureScore(q.infrastructureScore());e.setWorkforceScore(q.workforceScore());e.setThirdPartyScore(q.thirdPartyScore());e.setSupplyChainScore(q.supplyChainScore());e.setOperationalScore(q.operationalScore());e.setResilienceScore(round((q.visionScore()+q.continuityScore()+q.recoveryScore()+q.cyberScore()+q.infrastructureScore()+q.workforceScore()+q.thirdPartyScore()+q.supplyChainScore()+q.operationalScore())/9.0));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());e.setStatus(AutonomousEnterpriseResilienceStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseResilienceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseResilienceResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseResilienceResponse> search(String k,AutonomousEnterpriseResiliencePriority p,AutonomousEnterpriseResilienceStatus s,Pageable pg){return r.findAll(AutonomousEnterpriseResilienceSpecification.filter(k,p,s),pg).map(this::map);}
 public AutonomousEnterpriseResilienceResponse review(Long id,AutonomousEnterpriseResilienceActionRequest q){var e=find(id);need(e,AutonomousEnterpriseResilienceStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseResilienceStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseResilienceResponse approve(Long id,AutonomousEnterpriseResilienceActionRequest q){var e=find(id);need(e,AutonomousEnterpriseResilienceStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseResilienceStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseResilienceResponse reject(Long id,AutonomousEnterpriseResilienceActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseResilienceStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseResilienceStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseResilienceStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseResilienceResponse publish(Long id,AutonomousEnterpriseResilienceActionRequest q){var e=find(id);need(e,AutonomousEnterpriseResilienceStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseResilienceStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseResilienceAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseResilienceAnalyticsResponse(a.size(),cnt(a,AutonomousEnterpriseResilienceStatus.GENERATED),cnt(a,AutonomousEnterpriseResilienceStatus.REVIEWED),cnt(a,AutonomousEnterpriseResilienceStatus.APPROVED),cnt(a,AutonomousEnterpriseResilienceStatus.REJECTED),cnt(a,AutonomousEnterpriseResilienceStatus.PUBLISHED),avg(a,AutonomousEnterpriseResilience::getVisionScore),avg(a,AutonomousEnterpriseResilience::getContinuityScore),avg(a,AutonomousEnterpriseResilience::getRecoveryScore),avg(a,AutonomousEnterpriseResilience::getCyberScore),avg(a,AutonomousEnterpriseResilience::getInfrastructureScore),avg(a,AutonomousEnterpriseResilience::getWorkforceScore),avg(a,AutonomousEnterpriseResilience::getThirdPartyScore),avg(a,AutonomousEnterpriseResilience::getSupplyChainScore),avg(a,AutonomousEnterpriseResilience::getOperationalScore),avg(a,AutonomousEnterpriseResilience::getResilienceScore));}
 private long cnt(List<AutonomousEnterpriseResilience> a,AutonomousEnterpriseResilienceStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseResilience> a,ToDoubleFunction<AutonomousEnterpriseResilience> f){return round(a.stream().mapToDouble(f).average().orElse(0));}
 private double round(double v){return Math.round(v*100.0)/100.0;}
 private AutonomousEnterpriseResilience find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseResilienceNotFoundException(id));}
 private void need(AutonomousEnterpriseResilience e,AutonomousEnterpriseResilienceStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseResilienceResponse map(AutonomousEnterpriseResilience e){return new AutonomousEnterpriseResilienceResponse(e.getId(),e.getTitle(),e.getResilienceVision(),e.getBusinessContinuityPlan(),e.getDisasterRecoveryStrategy(),e.getCyberResilienceFramework(),e.getInfrastructureResilienceModel(),e.getWorkforceResilienceProgram(),e.getThirdPartyResilienceAssessment(),e.getSupplyChainResilienceStrategy(),e.getOperationalResilienceBlueprint(),e.getVisionScore(),e.getContinuityScore(),e.getRecoveryScore(),e.getCyberScore(),e.getInfrastructureScore(),e.getWorkforceScore(),e.getThirdPartyScore(),e.getSupplyChainScore(),e.getOperationalScore(),e.getResilienceScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
