package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.*;import ai.nexusone.enums.*;import ai.nexusone.exception.*;import ai.nexusone.repository.*;import ai.nexusone.specification.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;import java.math.*;import java.util.*;import java.util.function.ToDoubleFunction;
@Service @Transactional
public class AutonomousEnterpriseTransformationService {
 private final AutonomousEnterpriseTransformationRepository r;
 public AutonomousEnterpriseTransformationService(AutonomousEnterpriseTransformationRepository r){this.r=r;}
 public AutonomousEnterpriseTransformationResponse generate(AutonomousEnterpriseTransformationRequest q){var e=new AutonomousEnterpriseTransformation();apply(e,q);e.setStatus(AutonomousEnterpriseTransformationStatus.GENERATED);return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseTransformationResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseTransformationResponse> history(Pageable p){return r.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<AutonomousEnterpriseTransformationResponse> search(String k,AutonomousEnterpriseTransformationPriority p,AutonomousEnterpriseTransformationStatus s,Pageable page){return r.findAll(AutonomousEnterpriseTransformationSpecification.filter(k,p,s),page).map(this::map);}
 public AutonomousEnterpriseTransformationResponse review(Long id,AutonomousEnterpriseTransformationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseTransformationStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(AutonomousEnterpriseTransformationStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseTransformationResponse approve(Long id,AutonomousEnterpriseTransformationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseTransformationStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(AutonomousEnterpriseTransformationStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseTransformationResponse reject(Long id,AutonomousEnterpriseTransformationActionRequest q){var e=find(id);if(e.getStatus()!=AutonomousEnterpriseTransformationStatus.GENERATED&&e.getStatus()!=AutonomousEnterpriseTransformationStatus.REVIEWED)throw new IllegalStateException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(AutonomousEnterpriseTransformationStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(r.save(e));}
 public AutonomousEnterpriseTransformationResponse publish(Long id,AutonomousEnterpriseTransformationActionRequest q){var e=find(id);require(e,AutonomousEnterpriseTransformationStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(AutonomousEnterpriseTransformationStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(r.save(e));}
 @Transactional(readOnly=true) public AutonomousEnterpriseTransformationAnalyticsResponse analytics(){var a=r.findAll();return new AutonomousEnterpriseTransformationAnalyticsResponse(a.size(),count(a,AutonomousEnterpriseTransformationStatus.GENERATED),count(a,AutonomousEnterpriseTransformationStatus.REVIEWED),count(a,AutonomousEnterpriseTransformationStatus.APPROVED),count(a,AutonomousEnterpriseTransformationStatus.REJECTED),count(a,AutonomousEnterpriseTransformationStatus.PUBLISHED),avg(a,AutonomousEnterpriseTransformation::getOptimizationScore),avg(a,AutonomousEnterpriseTransformation::getSimulationScore),avg(a,AutonomousEnterpriseTransformation::getOrchestrationScore),avg(a,AutonomousEnterpriseTransformation::getRiskModelingScore),avg(a,AutonomousEnterpriseTransformation::getSecurityReadinessScore),avg(a,AutonomousEnterpriseTransformation::getDataReadinessScore),avg(a,AutonomousEnterpriseTransformation::getUseCaseValueScore),avg(a,AutonomousEnterpriseTransformation::getAdoptionReadinessScore),avg(a,AutonomousEnterpriseTransformation::getTransformationScore));}
 private long count(List<AutonomousEnterpriseTransformation>a,AutonomousEnterpriseTransformationStatus s){return a.stream().filter(x->x.getStatus()==s).count();}
 private double avg(List<AutonomousEnterpriseTransformation>a,ToDoubleFunction<AutonomousEnterpriseTransformation> f){return round(a.stream().mapToDouble(x->{Double v=f.applyAsDouble(x);return v==null?0:v;}).average().orElse(0));}
 private double round(double v){return BigDecimal.valueOf(v).setScale(2,RoundingMode.HALF_UP).doubleValue();}
 private void require(AutonomousEnterpriseTransformation e,AutonomousEnterpriseTransformationStatus s,String m){if(e.getStatus()!=s)throw new IllegalStateException(m);}
 private AutonomousEnterpriseTransformation find(Long id){return r.findById(id).orElseThrow(()->new AutonomousEnterpriseTransformationNotFoundException(id));}
 private void apply(AutonomousEnterpriseTransformation e,AutonomousEnterpriseTransformationRequest q){e.setTitle(q.title());e.setQuantumOptimizationStrategy(q.transformationVision());e.setQuantumSimulationModel(q.transformationRoadmap());e.setHybridQuantumClassicalOrchestration(q.operatingModelTransformation());e.setQuantumRiskModeling(q.workforceTransformation());e.setQuantumSecurityReadiness(q.processTransformation());e.setQuantumDataStrategy(q.technologyTransformation());e.setEnterpriseUseCases(q.customerTransformation());e.setTransformationRecommendations(q.transformationRiskAssessment());e.setOptimizationScore(q.visionScore());e.setSimulationScore(q.roadmapScore());e.setOrchestrationScore(q.operatingModelScore());e.setRiskModelingScore(q.workforceScore());e.setSecurityReadinessScore(q.processScore());e.setDataReadinessScore(q.technologyScore());e.setUseCaseValueScore(q.customerScore());e.setAdoptionReadinessScore(q.executionScore());e.setTransformationScore(round((q.visionScore()+q.roadmapScore()+q.operatingModelScore()+q.workforceScore()+q.processScore()+q.technologyScore()+q.customerScore()+q.executionScore())/8));e.setPriority(q.priority());e.setCreatedBy(q.createdBy());}
 private AutonomousEnterpriseTransformationResponse map(AutonomousEnterpriseTransformation e){return new AutonomousEnterpriseTransformationResponse(e.getId(),e.getTitle(),e.getQuantumOptimizationStrategy(),e.getQuantumSimulationModel(),e.getHybridQuantumClassicalOrchestration(),e.getQuantumRiskModeling(),e.getQuantumSecurityReadiness(),e.getQuantumDataStrategy(),e.getEnterpriseUseCases(),e.getTransformationRecommendations(),e.getOptimizationScore(),e.getSimulationScore(),e.getOrchestrationScore(),e.getRiskModelingScore(),e.getSecurityReadinessScore(),e.getDataReadinessScore(),e.getUseCaseValueScore(),e.getAdoptionReadinessScore(),e.getTransformationScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
