package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.ChairmanIntelligenceReport; import ai.nexusone.enums.*;
import ai.nexusone.exception.ChairmanIntelligenceNotFoundException; import ai.nexusone.repository.ChairmanIntelligenceRepository;
import java.time.LocalDateTime; import java.util.List; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ChairmanIntelligenceService {
 private final ChairmanIntelligenceRepository repo; public ChairmanIntelligenceService(ChairmanIntelligenceRepository r){repo=r;}
 @Transactional public ChairmanIntelligenceResponse generate(ChairmanIntelligenceRequest r){var e=new ChairmanIntelligenceReport();e.setTitle(r.title());e.setExecutiveSummary(r.executiveSummary());e.setChairmanAssessment(r.chairmanAssessment());e.setLongTermStrategy(r.longTermStrategy());e.setInvestmentRecommendation(r.investmentRecommendation());e.setShareholderImpact(r.shareholderImpact());e.setRevenueGrowthScore(r.revenueGrowthScore());e.setProfitabilityScore(r.profitabilityScore());e.setInnovationScore(r.innovationScore());e.setTransformationScore(r.transformationScore());e.setGovernanceScore(r.governanceScore());e.setRiskExposure(r.riskExposure());e.setChairmanScore(score(r));e.setPriority(r.priority());e.setStatus(ChairmanIntelligenceStatus.GENERATED);e.setCreatedBy(r.createdBy());return map(repo.save(e));}
 @Transactional(readOnly=true) public ChairmanIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<ChairmanIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<ChairmanIntelligenceResponse> search(String k,ChairmanPriority p,ChairmanIntelligenceStatus s,Pageable pg){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrExecutiveSummaryContainingIgnoreCaseOrInvestmentRecommendationContainingIgnoreCase(k,k,k,pg).map(this::map);if(p!=null)return repo.findByPriority(p,pg).map(this::map);if(s!=null)return repo.findByStatus(s,pg).map(this::map);return history(pg);}
 @Transactional public ChairmanIntelligenceResponse review(Long id,ChairmanActionRequest r){var e=find(id);need(e,ChairmanIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(ChairmanIntelligenceStatus.REVIEWED);e.setReviewedBy(r.actionBy());e.setReviewedAt(LocalDateTime.now());return map(repo.save(e));}
 @Transactional public ChairmanIntelligenceResponse approve(Long id,ChairmanActionRequest r){var e=find(id);need(e,ChairmanIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(ChairmanIntelligenceStatus.APPROVED);e.setDecidedBy(r.actionBy());e.setDecidedAt(LocalDateTime.now());return map(repo.save(e));}
 @Transactional public ChairmanIntelligenceResponse reject(Long id,ChairmanActionRequest r){var e=find(id);if(e.getStatus()!=ChairmanIntelligenceStatus.GENERATED&&e.getStatus()!=ChairmanIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(ChairmanIntelligenceStatus.REJECTED);e.setDecidedBy(r.actionBy());e.setDecidedAt(LocalDateTime.now());return map(repo.save(e));}
 @Transactional public ChairmanIntelligenceResponse execute(Long id,ChairmanActionRequest r){var e=find(id);need(e,ChairmanIntelligenceStatus.APPROVED,"Only APPROVED reports can be executed");e.setStatus(ChairmanIntelligenceStatus.EXECUTED);e.setExecutedBy(r.actionBy());e.setExecutedAt(LocalDateTime.now());return map(repo.save(e));}
 @Transactional(readOnly=true) public ChairmanAnalyticsResponse analytics(){List<ChairmanIntelligenceReport>a=repo.findAll();return new ChairmanAnalyticsResponse(a.size(),c(ChairmanIntelligenceStatus.GENERATED),c(ChairmanIntelligenceStatus.REVIEWED),c(ChairmanIntelligenceStatus.APPROVED),c(ChairmanIntelligenceStatus.REJECTED),c(ChairmanIntelligenceStatus.EXECUTED),avg(a,0),avg(a,1),avg(a,2),avg(a,3),avg(a,4),avg(a,5),round(a.stream().mapToDouble(ChairmanIntelligenceReport::getChairmanScore).average().orElse(0)));}
 private double score(ChairmanIntelligenceRequest r){return round(r.revenueGrowthScore()*.20+r.profitabilityScore()*.20+r.innovationScore()*.15+r.transformationScore()*.15+r.governanceScore()*.20+(100-r.riskExposure())*.10);}
 private double avg(List<ChairmanIntelligenceReport>a,int n){return round(a.stream().mapToDouble(x->switch(n){case 0->x.getRevenueGrowthScore();case 1->x.getProfitabilityScore();case 2->x.getInnovationScore();case 3->x.getTransformationScore();case 4->x.getGovernanceScore();default->x.getRiskExposure();}).average().orElse(0));}
 private long c(ChairmanIntelligenceStatus s){return repo.countByStatus(s);} private double round(double v){return Math.round(v*100.0)/100.0;}
 private void need(ChairmanIntelligenceReport e,ChairmanIntelligenceStatus s,String m){if(e.getStatus()!=s)throw new IllegalArgumentException(m);} private ChairmanIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new ChairmanIntelligenceNotFoundException(id));}
 private ChairmanIntelligenceResponse map(ChairmanIntelligenceReport e){return new ChairmanIntelligenceResponse(e.getId(),e.getTitle(),e.getExecutiveSummary(),e.getChairmanAssessment(),e.getLongTermStrategy(),e.getInvestmentRecommendation(),e.getShareholderImpact(),e.getRevenueGrowthScore(),e.getProfitabilityScore(),e.getInnovationScore(),e.getTransformationScore(),e.getGovernanceScore(),e.getRiskExposure(),e.getChairmanScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getExecutedBy(),e.getExecutedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
