package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.GeopoliticalIntelligenceReport; import ai.nexusone.enums.*;
import ai.nexusone.exception.GeopoliticalIntelligenceNotFoundException; import ai.nexusone.repository.GeopoliticalIntelligenceRepository;
import java.time.LocalDateTime; import java.util.List; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class GeopoliticalIntelligenceService{private final GeopoliticalIntelligenceRepository repo; public GeopoliticalIntelligenceService(GeopoliticalIntelligenceRepository r){repo=r;}
 @Transactional public GeopoliticalIntelligenceResponse generate(GeopoliticalIntelligenceRequest q){var x=new GeopoliticalIntelligenceReport();x.setTitle(q.title());x.setGeopoliticalOutlook(q.geopoliticalOutlook());x.setRegionalConflictAnalysis(q.regionalConflictAnalysis());x.setPoliticalStabilityAnalysis(q.politicalStabilityAnalysis());x.setSanctionsTradeAnalysis(q.sanctionsTradeAnalysis());x.setEnergyResourceSecurityAnalysis(q.energyResourceSecurityAnalysis());x.setSupplyChainGeopoliticalAnalysis(q.supplyChainGeopoliticalAnalysis());x.setRegulatorySovereigntyAnalysis(q.regulatorySovereigntyAnalysis());x.setDiplomaticRelationsAnalysis(q.diplomaticRelationsAnalysis());x.setStrategicRecommendations(q.strategicRecommendations());x.setRegionalStabilityScore(q.regionalStabilityScore());x.setPoliticalStabilityScore(q.politicalStabilityScore());x.setSanctionsExposureScore(q.sanctionsExposureScore());x.setEnergySecurityScore(q.energySecurityScore());x.setSupplyChainResilienceScore(q.supplyChainResilienceScore());x.setRegulatorySovereigntyScore(q.regulatorySovereigntyScore());x.setDiplomaticRelationsScore(q.diplomaticRelationsScore());x.setGeopoliticalIntelligenceScore(score(q));x.setPriority(q.priority());x.setStatus(GeopoliticalStatus.GENERATED);x.setCreatedBy(q.createdBy());return map(repo.save(x));}
 @Transactional(readOnly=true) public GeopoliticalIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<GeopoliticalIntelligenceResponse> history(Pageable p){return repo.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<GeopoliticalIntelligenceResponse> search(String k,GeopoliticalPriority p,GeopoliticalStatus s,Pageable pg){if(k!=null&&!k.isBlank())return repo.findByTitleContainingIgnoreCaseOrGeopoliticalOutlookContainingIgnoreCaseOrStrategicRecommendationsContainingIgnoreCase(k,k,k,pg).map(this::map);if(p!=null)return repo.findByPriority(p,pg).map(this::map);if(s!=null)return repo.findByStatus(s,pg).map(this::map);return history(pg);}
 @Transactional public GeopoliticalIntelligenceResponse review(Long id,GeopoliticalActionRequest q){var x=find(id);require(x,GeopoliticalStatus.GENERATED,"Only GENERATED reports can be reviewed");x.setStatus(GeopoliticalStatus.REVIEWED);x.setReviewedBy(q.actionBy());x.setReviewedAt(LocalDateTime.now());return map(repo.save(x));}
 @Transactional public GeopoliticalIntelligenceResponse approve(Long id,GeopoliticalActionRequest q){var x=find(id);require(x,GeopoliticalStatus.REVIEWED,"Only REVIEWED reports can be approved");x.setStatus(GeopoliticalStatus.APPROVED);x.setDecidedBy(q.actionBy());x.setDecidedAt(LocalDateTime.now());return map(repo.save(x));}
 @Transactional public GeopoliticalIntelligenceResponse reject(Long id,GeopoliticalActionRequest q){var x=find(id);if(x.getStatus()!=GeopoliticalStatus.GENERATED&&x.getStatus()!=GeopoliticalStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");x.setStatus(GeopoliticalStatus.REJECTED);x.setDecidedBy(q.actionBy());x.setDecidedAt(LocalDateTime.now());return map(repo.save(x));}
 @Transactional public GeopoliticalIntelligenceResponse publish(Long id,GeopoliticalActionRequest q){var x=find(id);require(x,GeopoliticalStatus.APPROVED,"Only APPROVED reports can be published");x.setStatus(GeopoliticalStatus.PUBLISHED);x.setPublishedBy(q.actionBy());x.setPublishedAt(LocalDateTime.now());return map(repo.save(x));}
 @Transactional(readOnly=true) public GeopoliticalAnalyticsResponse analytics(){List<GeopoliticalIntelligenceReport> a=repo.findAll();return new GeopoliticalAnalyticsResponse(a.size(),count(GeopoliticalStatus.GENERATED),count(GeopoliticalStatus.REVIEWED),count(GeopoliticalStatus.APPROVED),count(GeopoliticalStatus.REJECTED),count(GeopoliticalStatus.PUBLISHED),avg(a,0),avg(a,1),avg(a,2),avg(a,3),avg(a,4),avg(a,5),avg(a,6),round(a.stream().mapToDouble(GeopoliticalIntelligenceReport::getGeopoliticalIntelligenceScore).average().orElse(0)));}
 private double score(GeopoliticalIntelligenceRequest q){return round(q.regionalStabilityScore()*.15+q.politicalStabilityScore()*.15+q.sanctionsExposureScore()*.15+q.energySecurityScore()*.15+q.supplyChainResilienceScore()*.15+q.regulatorySovereigntyScore()*.10+q.diplomaticRelationsScore()*.15);}
 private double avg(List<GeopoliticalIntelligenceReport>a,int f){return round(a.stream().mapToDouble(x->switch(f){case 0->x.getRegionalStabilityScore();case 1->x.getPoliticalStabilityScore();case 2->x.getSanctionsExposureScore();case 3->x.getEnergySecurityScore();case 4->x.getSupplyChainResilienceScore();case 5->x.getRegulatorySovereigntyScore();default->x.getDiplomaticRelationsScore();}).average().orElse(0));}
 private long count(GeopoliticalStatus s){return repo.countByStatus(s);}private double round(double v){return Math.round(v*100.0)/100.0;}private void require(GeopoliticalIntelligenceReport x,GeopoliticalStatus s,String m){if(x.getStatus()!=s)throw new IllegalArgumentException(m);}private GeopoliticalIntelligenceReport find(Long id){return repo.findById(id).orElseThrow(()->new GeopoliticalIntelligenceNotFoundException(id));}
 private GeopoliticalIntelligenceResponse map(GeopoliticalIntelligenceReport x){return new GeopoliticalIntelligenceResponse(x.getId(),x.getTitle(),x.getGeopoliticalOutlook(),x.getRegionalConflictAnalysis(),x.getPoliticalStabilityAnalysis(),x.getSanctionsTradeAnalysis(),x.getEnergyResourceSecurityAnalysis(),x.getSupplyChainGeopoliticalAnalysis(),x.getRegulatorySovereigntyAnalysis(),x.getDiplomaticRelationsAnalysis(),x.getStrategicRecommendations(),x.getRegionalStabilityScore(),x.getPoliticalStabilityScore(),x.getSanctionsExposureScore(),x.getEnergySecurityScore(),x.getSupplyChainResilienceScore(),x.getRegulatorySovereigntyScore(),x.getDiplomaticRelationsScore(),x.getGeopoliticalIntelligenceScore(),x.getPriority(),x.getStatus(),x.getCreatedBy(),x.getReviewedBy(),x.getReviewedAt(),x.getDecidedBy(),x.getDecidedAt(),x.getPublishedBy(),x.getPublishedAt(),x.getCreatedAt(),x.getUpdatedAt());}}
