package ai.nexusone.service;
import ai.nexusone.dto.GitHubRepositoryResponse;
import org.springframework.beans.factory.annotation.Value; import org.springframework.core.ParameterizedTypeReference; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.client.RestClient; import java.nio.charset.StandardCharsets; import java.util.*;
@Service
public class GitHubService {
 private final RestClient client;
 public GitHubService(RestClient.Builder b,@Value("${nexusone.github.api-url}") String url,@Value("${nexusone.github.token:}") String token){RestClient.Builder x=b.baseUrl(url).defaultHeader(HttpHeaders.ACCEPT,"application/vnd.github+json").defaultHeader("X-GitHub-Api-Version","2022-11-28");if(token!=null&&!token.isBlank())x.defaultHeader(HttpHeaders.AUTHORIZATION,"Bearer "+token);client=x.build();}
 public List<GitHubRepositoryResponse> repositories(){List<Map<String,Object>> rows=client.get().uri("/user/repos?per_page=100&sort=updated").retrieve().body(new ParameterizedTypeReference<>(){});if(rows==null)return List.of();return rows.stream().map(r->new GitHubRepositoryResponse(str(r,"name"),str(r,"full_name"),str(r,"html_url"),str(r,"default_branch"),Boolean.TRUE.equals(r.get("private")))).toList();}
 public List<String> branches(String owner,String repo){List<Map<String,Object>> rows=client.get().uri("/repos/{owner}/{repo}/branches?per_page=100",owner,repo).retrieve().body(new ParameterizedTypeReference<>(){});if(rows==null)return List.of();return rows.stream().map(r->String.valueOf(r.get("name"))).toList();}
 public String defaultBranch(String owner,String repo){Map<String,Object> row=client.get().uri("/repos/{owner}/{repo}",owner,repo).retrieve().body(new ParameterizedTypeReference<>(){});return row==null?"main":String.valueOf(row.getOrDefault("default_branch","main"));}
 public List<Map<String,Object>> tree(String owner,String repo,String branch){Map<String,Object> body=client.get().uri("/repos/{owner}/{repo}/git/trees/{branch}?recursive=1",owner,repo,branch).retrieve().body(new ParameterizedTypeReference<>(){});Object t=body==null?null:body.get("tree");return t instanceof List<?> list?list.stream().filter(Map.class::isInstance).map(v->(Map<String,Object>)v).toList():List.of();}
 public String file(String owner,String repo,String path,String branch){Map<String,Object> body=client.get().uri(u->u.path("/repos/{owner}/{repo}/contents/{path}").queryParam("ref",branch).build(owner,repo,path)).retrieve().body(new ParameterizedTypeReference<>(){});if(body==null)return "";String c=String.valueOf(body.getOrDefault("content","")).replace("\n","");return new String(Base64.getDecoder().decode(c),StandardCharsets.UTF_8);}
 public String[] parse(String repositoryUrl){String v=repositoryUrl.trim().replace(".git","");int i=v.indexOf("github.com/");if(i<0)throw new IllegalArgumentException("Only GitHub repository URLs are supported");String[] p=v.substring(i+11).split("/");if(p.length<2)throw new IllegalArgumentException("Repository URL must contain owner and repository name");return new String[]{p[0],p[1]};}
 private String str(Map<String,Object> m,String k){return String.valueOf(m.getOrDefault(k,""));}
}
