package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.KnowledgeExperienceRecord; import ai.nexusone.enums.*; import ai.nexusone.exception.KnowledgeNotFoundException; import ai.nexusone.repository.KnowledgeExperienceRepository; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service public class KnowledgeFabricService{
 private final KnowledgeExperienceRepository repository; public KnowledgeFabricService(KnowledgeExperienceRepository r){repository=r;}
 @Transactional public KnowledgeResponse create(KnowledgeRequest r){var e=new KnowledgeExperienceRecord();e.setTitle(r.title());e.setCategory(r.category());e.setSourceModule(r.sourceModule());e.setIncidentId(r.incidentId());e.setDecisionId(r.decisionId());e.setExecutionId(r.executionId());e.setOutcomeId(r.outcomeId());e.setLearningId(r.learningId());e.setBusinessContext(r.businessContext());e.setProblemStatement(r.problemStatement());e.setSolutionSummary(r.solutionSummary());e.setLessonsLearned(r.lessonsLearned());e.setBestPractices(r.bestPractices());e.setReusablePlaybook(r.reusablePlaybook());e.setConfidenceScore(r.confidenceScore());e.setCreatedBy(r.createdBy());e.setStatus(r.confidenceScore()>=85?KnowledgeStatus.RECOMMENDED:KnowledgeStatus.DRAFT);return map(repository.save(e));}
 public KnowledgeResponse get(Long id){return map(entity(id));} public Page<KnowledgeResponse> history(Pageable p){return repository.findAll(p).map(this::map);}
 public Page<KnowledgeResponse> search(String keyword,KnowledgeCategory category,KnowledgeStatus status,Pageable p){if(keyword!=null&&!keyword.isBlank())return repository.findByTitleContainingIgnoreCaseOrProblemStatementContainingIgnoreCaseOrLessonsLearnedContainingIgnoreCase(keyword,keyword,keyword,p).map(this::map);if(category!=null)return repository.findByCategory(category,p).map(this::map);if(status!=null)return repository.findByStatus(status,p).map(this::map);return history(p);}
 @Transactional public KnowledgeResponse validate(Long id,ValidateKnowledgeRequest r){var e=entity(id);if(e.getStatus()==KnowledgeStatus.ARCHIVED)throw new IllegalArgumentException("Archived knowledge cannot be validated: "+id);e.setStatus(KnowledgeStatus.VALIDATED);e.setValidatedBy(r.validatedBy());e.setValidatedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public KnowledgeResponse archive(Long id){var e=entity(id);e.setStatus(KnowledgeStatus.ARCHIVED);return map(repository.save(e));}
 @Transactional public KnowledgeResponse reuse(Long id){var e=entity(id);if(e.getStatus()==KnowledgeStatus.ARCHIVED)throw new IllegalArgumentException("Archived knowledge cannot be reused: "+id);e.setReuseCount(e.getReuseCount()+1);return map(repository.save(e));}
 public KnowledgeAnalyticsResponse analytics(){var all=repository.findAll();long total=all.size(),draft=repository.countByStatus(KnowledgeStatus.DRAFT),validated=repository.countByStatus(KnowledgeStatus.VALIDATED),recommended=repository.countByStatus(KnowledgeStatus.RECOMMENDED),archived=repository.countByStatus(KnowledgeStatus.ARCHIVED),reuses=all.stream().mapToLong(KnowledgeExperienceRecord::getReuseCount).sum();double confidence=all.isEmpty()?0:round(all.stream().mapToDouble(KnowledgeExperienceRecord::getConfidenceScore).average().orElse(0)),rate=total==0?0:round(all.stream().filter(x->x.getReuseCount()>0).count()*100.0/total);return new KnowledgeAnalyticsResponse(total,draft,validated,recommended,archived,confidence,reuses,rate);}
 private KnowledgeExperienceRecord entity(Long id){return repository.findById(id).orElseThrow(()->new KnowledgeNotFoundException(id));} private double round(double v){return Math.round(v*100.0)/100.0;}
 private KnowledgeResponse map(KnowledgeExperienceRecord e){return new KnowledgeResponse(e.getId(),e.getTitle(),e.getCategory(),e.getSourceModule(),e.getIncidentId(),e.getDecisionId(),e.getExecutionId(),e.getOutcomeId(),e.getLearningId(),e.getBusinessContext(),e.getProblemStatement(),e.getSolutionSummary(),e.getLessonsLearned(),e.getBestPractices(),e.getReusablePlaybook(),e.getConfidenceScore(),e.getReuseCount(),e.getStatus(),e.getCreatedBy(),e.getValidatedBy(),e.getValidatedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
