package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.LearningRecord; import ai.nexusone.enums.*; import ai.nexusone.exception.LearningNotFoundException; import ai.nexusone.repository.LearningRecordRepository;
import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.List;
@Service
public class LearningOptimizationService {
 private final LearningRecordRepository repository; public LearningOptimizationService(LearningRecordRepository repository){this.repository=repository;}
 @Transactional public LearningResponse learn(LearningRequest r){LearningRecord e=new LearningRecord();e.setOutcomeId(r.outcomeId());e.setExecutionId(r.executionId());e.setApplicationName(r.applicationName());e.setEnvironment(r.environment().toUpperCase());e.setOptimizationArea(r.optimizationArea());e.setObservedScore(r.observedScore());e.setTargetScore(r.targetScore());e.setEvidence(r.evidence());e.setCreatedBy(r.createdBy());assess(e);return map(repository.save(e));}
 @Transactional public LearningResponse apply(Long id,ApplyLearningRequest r){LearningRecord e=getEntity(id);if(e.getStatus()==LearningStatus.APPLIED)throw new IllegalArgumentException("Learning recommendation is already applied: "+id);e.setStatus(LearningStatus.APPLIED);e.setAppliedBy(r.appliedBy());e.setAppliedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public LearningResponse reject(Long id){LearningRecord e=getEntity(id);if(e.getStatus()==LearningStatus.APPLIED)throw new IllegalArgumentException("Applied learning cannot be rejected: "+id);e.setStatus(LearningStatus.REJECTED);return map(repository.save(e));}
 public LearningResponse get(Long id){return map(getEntity(id));} public List<LearningResponse> byOutcome(Long id){return repository.findByOutcomeIdOrderByCreatedAtDesc(id).stream().map(this::map).toList();} public Page<LearningResponse> history(Pageable p){return repository.findAll(p).map(this::map);}
 public LearningAnalyticsResponse analytics(){List<LearningRecord> all=repository.findAll();long total=all.size(),d=repository.countByStatus(LearningStatus.DISCOVERED),r=repository.countByStatus(LearningStatus.RECOMMENDED),a=repository.countByStatus(LearningStatus.APPLIED),x=repository.countByStatus(LearningStatus.REJECTED);double gap=avg(all.stream().map(LearningRecord::getImprovementGap).toList()),confidence=avg(all.stream().map(LearningRecord::getConfidenceScore).toList()),rate=total==0?0:round(a*100.0/total);return new LearningAnalyticsResponse(total,d,r,a,x,gap,confidence,rate);}
 private void assess(LearningRecord e){double gap=round(Math.max(0,e.getTargetScore()-e.getObservedScore()));e.setImprovementGap(gap);e.setConfidenceScore(round(Math.min(99,65+gap*.65)));e.setPriorityScore((int)Math.min(100,Math.round(gap*2)));e.setStatus(gap<5?LearningStatus.DISCOVERED:LearningStatus.RECOMMENDED);e.setLearningSummary(gap==0?"Observed outcome already meets the optimization target.":"A measurable optimization gap of "+gap+" points was learned from the outcome.");e.setOptimizationRecommendation(recommend(e.getOptimizationArea(),gap));}
 private String recommend(OptimizationArea a,double gap){if(gap<5)return "Preserve the current execution pattern and continue monitoring for drift.";return switch(a){case AVAILABILITY->"Increase redundancy, validate readiness probes and review failover policy.";case PERFORMANCE->"Tune resource limits, concurrency and latency-sensitive execution steps.";case RELIABILITY->"Reduce recurring errors, strengthen rollback controls and automate recovery verification.";case COST->"Right-size resources, remove idle capacity and validate savings against service objectives.";case BUSINESS_KPI->"Align execution policy with the weakest business KPI and measure the next outcome.";case BALANCED->"Apply a balanced optimization plan across reliability, performance, cost and business impact.";};}
 private LearningRecord getEntity(Long id){return repository.findById(id).orElseThrow(()->new LearningNotFoundException(id));} private double avg(List<Double> v){return v.isEmpty()?0:round(v.stream().mapToDouble(Double::doubleValue).average().orElse(0));} private double round(double v){return Math.round(v*100.0)/100.0;}
 private LearningResponse map(LearningRecord e){return new LearningResponse(e.getId(),e.getOutcomeId(),e.getExecutionId(),e.getApplicationName(),e.getEnvironment(),e.getOptimizationArea(),e.getObservedScore(),e.getTargetScore(),e.getImprovementGap(),e.getConfidenceScore(),e.getPriorityScore(),e.getStatus(),e.getLearningSummary(),e.getOptimizationRecommendation(),e.getEvidence(),e.getCreatedBy(),e.getAppliedBy(),e.getAppliedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
