package ai.nexusone.service;
import ai.nexusone.dto.*;import ai.nexusone.entity.MarketIntelligenceReport;import ai.nexusone.enums.*;import ai.nexusone.exception.MarketIntelligenceNotFoundException;import ai.nexusone.repository.MarketIntelligenceRepository;
import java.time.LocalDateTime;import java.util.List;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class MarketIntelligenceService{
 private final MarketIntelligenceRepository repository; public MarketIntelligenceService(MarketIntelligenceRepository r){repository=r;}
 @Transactional public MarketIntelligenceResponse generate(MarketIntelligenceRequest q){var e=new MarketIntelligenceReport();e.setTitle(q.title());e.setMarketLandscape(q.marketLandscape());e.setCompetitorAnalysis(q.competitorAnalysis());e.setDifferentiationStrategy(q.differentiationStrategy());e.setOpportunityAssessment(q.opportunityAssessment());e.setStrategicRecommendation(q.strategicRecommendation());e.setMarketAttractivenessScore(q.marketAttractivenessScore());e.setCompetitivePositionScore(q.competitivePositionScore());e.setDifferentiationScore(q.differentiationScore());e.setInnovationStrengthScore(q.innovationStrengthScore());e.setExecutionReadinessScore(q.executionReadinessScore());e.setMarketThreatExposure(q.marketThreatExposure());e.setMarketCompetitiveConfidenceScore(score(q));e.setPriority(q.priority());e.setStatus(MarketIntelligenceStatus.GENERATED);e.setCreatedBy(q.createdBy());return map(repository.save(e));}
 @Transactional(readOnly=true) public MarketIntelligenceResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<MarketIntelligenceResponse> history(Pageable p){return repository.findAll(p).map(this::map);}
 @Transactional(readOnly=true) public Page<MarketIntelligenceResponse> search(String k,MarketPriority p,MarketIntelligenceStatus s,Pageable page){if(k!=null&&!k.isBlank())return repository.findByTitleContainingIgnoreCaseOrMarketLandscapeContainingIgnoreCaseOrCompetitorAnalysisContainingIgnoreCase(k,k,k,page).map(this::map);if(p!=null)return repository.findByPriority(p,page).map(this::map);if(s!=null)return repository.findByStatus(s,page).map(this::map);return history(page);}
 @Transactional public MarketIntelligenceResponse review(Long id,MarketActionRequest q){var e=find(id);require(e,MarketIntelligenceStatus.GENERATED,"Only GENERATED reports can be reviewed");e.setStatus(MarketIntelligenceStatus.REVIEWED);e.setReviewedBy(q.actionBy());e.setReviewedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public MarketIntelligenceResponse approve(Long id,MarketActionRequest q){var e=find(id);require(e,MarketIntelligenceStatus.REVIEWED,"Only REVIEWED reports can be approved");e.setStatus(MarketIntelligenceStatus.APPROVED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public MarketIntelligenceResponse reject(Long id,MarketActionRequest q){var e=find(id);if(e.getStatus()!=MarketIntelligenceStatus.GENERATED&&e.getStatus()!=MarketIntelligenceStatus.REVIEWED)throw new IllegalArgumentException("Only GENERATED or REVIEWED reports can be rejected");e.setStatus(MarketIntelligenceStatus.REJECTED);e.setDecidedBy(q.actionBy());e.setDecidedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public MarketIntelligenceResponse publish(Long id,MarketActionRequest q){var e=find(id);require(e,MarketIntelligenceStatus.APPROVED,"Only APPROVED reports can be published");e.setStatus(MarketIntelligenceStatus.PUBLISHED);e.setPublishedBy(q.actionBy());e.setPublishedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional(readOnly=true) public MarketAnalyticsResponse analytics(){List<MarketIntelligenceReport> r=repository.findAll();return new MarketAnalyticsResponse(r.size(),count(MarketIntelligenceStatus.GENERATED),count(MarketIntelligenceStatus.REVIEWED),count(MarketIntelligenceStatus.APPROVED),count(MarketIntelligenceStatus.REJECTED),count(MarketIntelligenceStatus.PUBLISHED),avg(r,0),avg(r,1),avg(r,2),avg(r,3),avg(r,4),avg(r,5),round(r.stream().mapToDouble(MarketIntelligenceReport::getMarketCompetitiveConfidenceScore).average().orElse(0)));}
 private double score(MarketIntelligenceRequest q){return round(q.marketAttractivenessScore()*.20+q.competitivePositionScore()*.20+q.differentiationScore()*.20+q.innovationStrengthScore()*.15+q.executionReadinessScore()*.15+(100-q.marketThreatExposure())*.10);}
 private double avg(List<MarketIntelligenceReport> r,int f){return round(r.stream().mapToDouble(e->switch(f){case 0->e.getMarketAttractivenessScore();case 1->e.getCompetitivePositionScore();case 2->e.getDifferentiationScore();case 3->e.getInnovationStrengthScore();case 4->e.getExecutionReadinessScore();default->e.getMarketThreatExposure();}).average().orElse(0));}
 private long count(MarketIntelligenceStatus s){return repository.countByStatus(s);} private double round(double v){return Math.round(v*100.0)/100.0;} private void require(MarketIntelligenceReport e,MarketIntelligenceStatus s,String m){if(e.getStatus()!=s)throw new IllegalArgumentException(m);} private MarketIntelligenceReport find(Long id){return repository.findById(id).orElseThrow(()->new MarketIntelligenceNotFoundException(id));}
 private MarketIntelligenceResponse map(MarketIntelligenceReport e){return new MarketIntelligenceResponse(e.getId(),e.getTitle(),e.getMarketLandscape(),e.getCompetitorAnalysis(),e.getDifferentiationStrategy(),e.getOpportunityAssessment(),e.getStrategicRecommendation(),e.getMarketAttractivenessScore(),e.getCompetitivePositionScore(),e.getDifferentiationScore(),e.getInnovationStrengthScore(),e.getExecutionReadinessScore(),e.getMarketThreatExposure(),e.getMarketCompetitiveConfidenceScore(),e.getPriority(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getDecidedBy(),e.getDecidedAt(),e.getPublishedBy(),e.getPublishedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
