package ai.nexusone.service;
import ai.nexusone.dto.request.ObservabilityQueryRequest; import ai.nexusone.dto.response.*; import ai.nexusone.entity.ObservabilityAnalysis; import ai.nexusone.repository.ObservabilityAnalysisRepository; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import java.time.Instant; import java.util.*;
@Service public class ObservabilityCopilotService{
 private final ObservabilityAnalysisRepository repo; private final Map<String,ServiceHealthResponse> services;
 public ObservabilityCopilotService(ObservabilityAnalysisRepository r){repo=r;services=seed();}
 public ObservabilityOverviewResponse overview(){long healthy=services.values().stream().filter(x->"HEALTHY".equals(x.status())).count();long degraded=services.size()-healthy;long critical=services.values().stream().filter(x->"CRITICAL".equals(x.status())).count();return new ObservabilityOverviewResponse(services.size(),healthy,degraded,critical,repo.count());}
 public List<ServiceHealthResponse> services(){return new ArrayList<>(services.values());}
 public ObservabilityInsightResponse insight(String name){return build(service(name),"Generate a correlated observability assessment.");}
 public ObservabilityInsightResponse analyze(ObservabilityQueryRequest q){var x=build(service(q.serviceName()),q.question());repo.save(new ObservabilityAnalysis(x.serviceName(),x.question(),x.observation(),x.impact(),x.recommendation(),x.confidence(),x.severity()));return x;}
 public Page<ObservabilityAnalysis> history(int p,int s){return repo.findAllByOrderByCreatedAtDesc(page(p,s));}
 private PageRequest page(int p,int s){return PageRequest.of(Math.max(0,p),Math.min(100,Math.max(1,s)),Sort.by("createdAt").descending());}
 private ServiceHealthResponse service(String n){var x=services.get(n);if(x==null)throw new NoSuchElementException("Service not found: "+n);return x;}
 private ObservabilityInsightResponse build(ServiceHealthResponse x,String q){
  if("checkout-service".equals(x.serviceName()))return resp(x,q,"Latency and error rate increased after database saturation.","Checkout requests may fail during peak traffic.","Reduce retry pressure, validate pool capacity, and watch 5xx recovery.",.93,"CRITICAL",List.of("Latency rose with DB pool usage","Retries correlate with 5xx growth"),List.of("Inspect slow queries","Apply guarded throttling","Validate checkout smoke test"));
  if("order-worker".equals(x.serviceName()))return resp(x,q,"Queue lag correlates with CPU saturation.","Order processing time may exceed the target.","Increase approved worker capacity and monitor backlog drain.",.87,"HIGH",List.of("Queue lag and CPU rose together","HPA is near maximum"),List.of("Review replica ceiling","Scale workers","Verify queue lag reduction"));
  return resp(x,q,"Service telemetry remains within normal thresholds.","No immediate customer impact is indicated.","Continue monitoring current SLO signals.",.91,"LOW",List.of("Latency stable","Error rate below threshold"),List.of("Keep alerting enabled","Review after next deployment"));}
 private ObservabilityInsightResponse resp(ServiceHealthResponse x,String q,String o,String i,String r,double c,String s,List<String> co,List<String>a){return new ObservabilityInsightResponse(x.serviceName(),q,o,i,r,c,s,co,a,Instant.now());}
 private Map<String,ServiceHealthResponse> seed(){Map<String,ServiceHealthResponse>m=new LinkedHashMap<>();m.put("checkout-service",new ServiceHealthResponse("checkout-service","production","CRITICAL",62,850,.18,420,99.10,"mysql",Instant.parse("2026-09-18T11:45:00Z"),List.of("p95 latency 850 ms","HTTP 5xx 18%","DB pool 94%")));m.put("order-worker",new ServiceHealthResponse("order-worker","production","DEGRADED",74,610,.06,280,99.55,"order-queue",Instant.parse("2026-09-18T11:44:00Z"),List.of("Queue lag rising","CPU 82%","HPA near maximum")));m.put("customer-api",new ServiceHealthResponse("customer-api","staging","HEALTHY",96,180,.01,510,99.98,"customer-db",Instant.parse("2026-09-18T11:43:00Z"),List.of("Latency stable","Error rate normal","All probes ready")));return m;}
}
