package ai.nexusone.service;
import ai.nexusone.dto.*; import org.springframework.stereotype.Service; import java.util.*; import java.util.regex.*;
@Service
public class RepositoryAnalyzerService {
 private final GitHubService github; public RepositoryAnalyzerService(GitHubService g){github=g;}
 public AnalysisResponse analyze(String url,String requestedBranch){String[] p=github.parse(url);String branch=requestedBranch==null||requestedBranch.isBlank()?github.defaultBranch(p[0],p[1]):requestedBranch;List<RiskFinding> f=new ArrayList<>();List<Map<String,Object>> files=github.tree(p[0],p[1],branch).stream().filter(x->"blob".equals(x.get("type"))).filter(x->eligible(String.valueOf(x.get("path")))).limit(80).toList();for(Map<String,Object>x:files){String path=String.valueOf(x.get("path"));Object size=x.get("size");if(size instanceof Number n&&n.longValue()>300_000)continue;String c=github.file(p[0],p[1],path,branch);match(f,path,c,"HIGH","HARDCODED_SECRET",Pattern.compile("(?i)(password|secret|api[_-]?key|token)\\s*[=:]\\s*[\\\"](?!\\$\\{|\\{\\{|<)[^\\\"]{4,}[\\\"]"),"Potential hardcoded secret");match(f,path,c,"MEDIUM","PRINT_STACK_TRACE",Pattern.compile("\\.printStackTrace\\s*\\("),"Avoid printStackTrace; use structured logging");match(f,path,c,"LOW","CONSOLE_OUTPUT",Pattern.compile("System\\.out\\.print|console\\.log\\s*\\("),"Debug output found");match(f,path,c,"LOW","PENDING_WORK",Pattern.compile("(?i)\\b(TODO|FIXME)\\b"),"Pending work marker found");}
 int high=(int)f.stream().filter(x->x.severity().equals("HIGH")).count(),med=(int)f.stream().filter(x->x.severity().equals("MEDIUM")).count(),low=(int)f.stream().filter(x->x.severity().equals("LOW")).count();int score=Math.max(0,100-high*20-med*10-low*5);String status=score>=80?"HEALTHY":score>=50?"WARNING":"CRITICAL";return new AnalysisResponse(url,branch,score,status,f);}
 private boolean eligible(String p){String v=p.toLowerCase();return v.endsWith(".java")||v.endsWith(".js")||v.endsWith(".jsx")||v.endsWith(".ts")||v.endsWith(".tsx")||v.endsWith(".py")||v.endsWith(".properties")||v.endsWith(".yml")||v.endsWith(".yaml");}
 private void match(List<RiskFinding> out,String path,String c,String s,String r,Pattern p,String m){if(p.matcher(c).find())out.add(new RiskFinding(s,r,path,m));}
}
