package ai.nexusone.service;
import ai.nexusone.dto.*; import ai.nexusone.entity.*; import ai.nexusone.enums.*; import ai.nexusone.exception.*; import ai.nexusone.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.*;
@Service public class StrategicIntelligenceService {
 private final StrategicInitiativeRepository repository; public StrategicIntelligenceService(StrategicInitiativeRepository r){repository=r;}
 @Transactional public StrategicInitiativeResponse create(StrategicInitiativeRequest r){var e=new StrategicInitiative();apply(e,r);e.setPriorityScore(score(r.alignmentScore(),r.valueScore(),r.riskScore()));return map(repository.save(e));}
 @Transactional public StrategicInitiativeResponse generate(GenerateStrategyRequest r){int n=Optional.ofNullable(r.evidence()).orElse(List.of()).size();double alignment=clamp(70+n*3),value=clamp(68+n*4),risk=clamp(45-n*2);var e=new StrategicInitiative();e.setTitle(r.title());e.setStrategicType(r.strategicType());e.setBusinessObjective(r.businessObjective());e.setCurrentState(r.currentState());e.setTargetState(r.targetState());e.setBusinessImpact("Expected strategic value is based on "+n+" supplied evidence signals.");e.setRecommendation("Validate assumptions, assign an accountable owner and execute through governed milestones.");e.setAlignmentScore(alignment);e.setValueScore(value);e.setRiskScore(risk);e.setPriorityScore(score(alignment,value,risk));e.setStatus(StrategicStatus.ANALYZED);e.setCreatedBy(r.createdBy());return map(repository.save(e));}
 @Transactional(readOnly=true) public Page<StrategicInitiativeResponse> history(Pageable p){return repository.findAll(p).map(this::map);} @Transactional(readOnly=true) public StrategicInitiativeResponse get(Long id){return map(find(id));}
 @Transactional(readOnly=true) public Page<StrategicInitiativeResponse> search(String keyword,StrategicType type,StrategicStatus status,Pageable p){if(keyword!=null&&!keyword.isBlank())return repository.findByTitleContainingIgnoreCaseOrBusinessObjectiveContainingIgnoreCaseOrRecommendationContainingIgnoreCase(keyword,keyword,keyword,p).map(this::map);if(type!=null)return repository.findByStrategicType(type,p).map(this::map);if(status!=null)return repository.findByStatus(status,p).map(this::map);return history(p);}
 @Transactional public StrategicInitiativeResponse analyze(Long id){var e=find(id);ensureMutable(e);e.setPriorityScore(score(e.getAlignmentScore(),e.getValueScore(),e.getRiskScore()));e.setStatus(StrategicStatus.ANALYZED);return map(repository.save(e));}
 @Transactional public StrategicInitiativeResponse review(Long id,StrategicActionRequest r){var e=find(id);ensureMutable(e);if(e.getStatus()!=StrategicStatus.ANALYZED)throw new IllegalArgumentException("Only ANALYZED initiatives can be reviewed");e.setStatus(StrategicStatus.REVIEWED);e.setReviewedBy(r.actionBy());e.setReviewedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public StrategicInitiativeResponse approve(Long id,StrategicActionRequest r){var e=find(id);ensureMutable(e);if(e.getStatus()!=StrategicStatus.REVIEWED)throw new IllegalArgumentException("Only REVIEWED initiatives can be approved");e.setStatus(StrategicStatus.APPROVED);e.setApprovedBy(r.actionBy());e.setApprovedAt(LocalDateTime.now());return map(repository.save(e));}
 @Transactional public StrategicInitiativeResponse archive(Long id){var e=find(id);e.setStatus(StrategicStatus.ARCHIVED);return map(repository.save(e));}
 @Transactional(readOnly=true) public StrategicAnalyticsResponse analytics(){var all=repository.findAll();return new StrategicAnalyticsResponse(all.size(),count(StrategicStatus.DRAFT),count(StrategicStatus.ANALYZED),count(StrategicStatus.REVIEWED),count(StrategicStatus.APPROVED),count(StrategicStatus.ARCHIVED),avg(all,"a"),avg(all,"v"),avg(all,"r"),round(all.stream().filter(x->x.getStatus()!=StrategicStatus.ARCHIVED).mapToDouble(StrategicInitiative::getPriorityScore).average().orElse(0)));}
 private long count(StrategicStatus s){return repository.countByStatus(s);} private double avg(List<StrategicInitiative> x,String k){return round(x.stream().mapToDouble(e->k.equals("a")?e.getAlignmentScore():k.equals("v")?e.getValueScore():e.getRiskScore()).average().orElse(0));}
 private void apply(StrategicInitiative e,StrategicInitiativeRequest r){e.setTitle(r.title());e.setStrategicType(r.strategicType());e.setBusinessObjective(r.businessObjective());e.setCurrentState(r.currentState());e.setTargetState(r.targetState());e.setBusinessImpact(r.businessImpact());e.setRecommendation(r.recommendation());e.setAlignmentScore(r.alignmentScore());e.setValueScore(r.valueScore());e.setRiskScore(r.riskScore());e.setCreatedBy(r.createdBy());}
 private double score(double a,double v,double r){return round(a*.4+v*.4+(100-r)*.2);} private double clamp(double v){return Math.max(0,Math.min(100,v));} private double round(double v){return Math.round(v*100.0)/100.0;} private StrategicInitiative find(Long id){return repository.findById(id).orElseThrow(()->new StrategicInitiativeNotFoundException(id));} private void ensureMutable(StrategicInitiative e){if(e.getStatus()==StrategicStatus.ARCHIVED)throw new IllegalArgumentException("Archived initiative cannot be modified: "+e.getId());}
 private StrategicInitiativeResponse map(StrategicInitiative e){return new StrategicInitiativeResponse(e.getId(),e.getTitle(),e.getStrategicType(),e.getBusinessObjective(),e.getCurrentState(),e.getTargetState(),e.getBusinessImpact(),e.getRecommendation(),e.getAlignmentScore(),e.getValueScore(),e.getRiskScore(),e.getPriorityScore(),e.getStatus(),e.getCreatedBy(),e.getReviewedBy(),e.getReviewedAt(),e.getApprovedBy(),e.getApprovedAt(),e.getCreatedAt(),e.getUpdatedAt());}
}
