package ai.nexusone.controller;
import ai.nexusone.dto.*; import ai.nexusone.enums.*; import ai.nexusone.service.GeopoliticalIntelligenceService; import jakarta.validation.Valid; import java.util.Map;
import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/geopolitical-intelligence") @CrossOrigin(origins="http://localhost:5173") public class GeopoliticalIntelligenceController{private final GeopoliticalIntelligenceService service;public GeopoliticalIntelligenceController(GeopoliticalIntelligenceService s){service=s;}
@PostMapping("/generate") ResponseEntity<GeopoliticalIntelligenceResponse> generate(@Valid @RequestBody GeopoliticalIntelligenceRequest q){return ResponseEntity.status(HttpStatus.CREATED).body(service.generate(q));}
@GetMapping("/{id}") GeopoliticalIntelligenceResponse get(@PathVariable Long id){return service.get(id);}
@GetMapping("/history") Page<GeopoliticalIntelligenceResponse> history(@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC) Pageable p){return service.history(p);}
@GetMapping("/search") Page<GeopoliticalIntelligenceResponse> search(@RequestParam(required=false)String keyword,@RequestParam(required=false)GeopoliticalPriority priority,@RequestParam(required=false)GeopoliticalStatus status,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable p){return service.search(keyword,priority,status,p);}
@PostMapping("/{id}/review") GeopoliticalIntelligenceResponse review(@PathVariable Long id,@Valid @RequestBody GeopoliticalActionRequest q){return service.review(id,q);}@PostMapping("/{id}/approve") GeopoliticalIntelligenceResponse approve(@PathVariable Long id,@Valid @RequestBody GeopoliticalActionRequest q){return service.approve(id,q);}@PostMapping("/{id}/reject") GeopoliticalIntelligenceResponse reject(@PathVariable Long id,@Valid @RequestBody GeopoliticalActionRequest q){return service.reject(id,q);}@PostMapping("/{id}/publish") GeopoliticalIntelligenceResponse publish(@PathVariable Long id,@Valid @RequestBody GeopoliticalActionRequest q){return service.publish(id,q);}
@GetMapping({"/analytics","/dashboard"}) GeopoliticalAnalyticsResponse analytics(){return service.analytics();}@GetMapping("/health") Map<String,String> health(){return Map.of("status","UP","mode","AUTONOMOUS_ENTERPRISE_GEOPOLITICAL_INTELLIGENCE");}}
