package ai.nexusone.controller;
import ai.nexusone.dto.*; import ai.nexusone.enums.*; import ai.nexusone.service.KnowledgeFabricService; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/knowledge-fabric") @CrossOrigin(origins="http://localhost:5173") public class KnowledgeFabricController{
 private final KnowledgeFabricService service; public KnowledgeFabricController(KnowledgeFabricService s){service=s;}
 @PostMapping("/create") public ResponseEntity<KnowledgeResponse> create(@Valid @RequestBody KnowledgeRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(r));}
 @GetMapping("/{id}") public KnowledgeResponse get(@PathVariable Long id){return service.get(id);} @GetMapping("/history") public Page<KnowledgeResponse> history(@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC) Pageable p){return service.history(p);}
 @GetMapping("/search") public Page<KnowledgeResponse> search(@RequestParam(required=false)String keyword,@RequestParam(required=false)KnowledgeCategory category,@RequestParam(required=false)KnowledgeStatus status,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable p){return service.search(keyword,category,status,p);}
 @GetMapping("/analytics") public KnowledgeAnalyticsResponse analytics(){return service.analytics();} @PostMapping("/{id}/validate") public KnowledgeResponse validate(@PathVariable Long id,@Valid @RequestBody ValidateKnowledgeRequest r){return service.validate(id,r);} @PostMapping("/{id}/archive") public KnowledgeResponse archive(@PathVariable Long id){return service.archive(id);} @PostMapping("/{id}/reuse") public KnowledgeResponse reuse(@PathVariable Long id){return service.reuse(id);} @GetMapping("/health") public Map<String,String> health(){return Map.of("status","UP","mode","ENTERPRISE_KNOWLEDGE_REUSE");}
}
