package ai.nexusone.controller;
import ai.nexusone.dto.*; import ai.nexusone.enums.*; import ai.nexusone.service.*; import jakarta.validation.Valid; import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.Map;
@RestController @RequestMapping("/api/strategic-intelligence") @CrossOrigin(origins="http://localhost:5173") public class StrategicIntelligenceController {
 private final StrategicIntelligenceService service; public StrategicIntelligenceController(StrategicIntelligenceService s){service=s;}
 @PostMapping("/create") ResponseEntity<StrategicInitiativeResponse> create(@Valid @RequestBody StrategicInitiativeRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.create(r));}
 @PostMapping("/generate") ResponseEntity<StrategicInitiativeResponse> generate(@Valid @RequestBody GenerateStrategyRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.generate(r));}
 @GetMapping("/{id}") StrategicInitiativeResponse get(@PathVariable Long id){return service.get(id);} @GetMapping("/history") Page<StrategicInitiativeResponse> history(@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC) Pageable p){return service.history(p);}
 @GetMapping("/search") Page<StrategicInitiativeResponse> search(@RequestParam(required=false)String keyword,@RequestParam(required=false)StrategicType type,@RequestParam(required=false)StrategicStatus status,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable p){return service.search(keyword,type,status,p);}
 @PostMapping("/{id}/analyze") StrategicInitiativeResponse analyze(@PathVariable Long id){return service.analyze(id);} @PostMapping("/{id}/review") StrategicInitiativeResponse review(@PathVariable Long id,@Valid @RequestBody StrategicActionRequest r){return service.review(id,r);} @PostMapping("/{id}/approve") StrategicInitiativeResponse approve(@PathVariable Long id,@Valid @RequestBody StrategicActionRequest r){return service.approve(id,r);} @PostMapping("/{id}/archive") StrategicInitiativeResponse archive(@PathVariable Long id){return service.archive(id);} @GetMapping("/analytics") StrategicAnalyticsResponse analytics(){return service.analytics();} @GetMapping("/health") Map<String,String> health(){return Map.of("status","UP","mode","AUTONOMOUS_ENTERPRISE_STRATEGIC_INTELLIGENCE");}
}
