package ai.nexusone.controller;
import ai.nexusone.dto.*; import ai.nexusone.enums.*; import ai.nexusone.service.*; import jakarta.validation.Valid; import java.util.Map;
import org.springframework.data.domain.*; import org.springframework.data.web.PageableDefault; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/strategic-enterprise-brain") @CrossOrigin(origins="http://localhost:5173")
public class StrategicEnterpriseBrainController { private final StrategicEnterpriseBrainService service; public StrategicEnterpriseBrainController(StrategicEnterpriseBrainService s){service=s;}
 @PostMapping("/generate") ResponseEntity<StrategicEnterpriseBrainResponse> generate(@Valid @RequestBody StrategicEnterpriseBrainRequest q){return ResponseEntity.status(HttpStatus.CREATED).body(service.generate(q));}
 @GetMapping("/{id}") StrategicEnterpriseBrainResponse get(@PathVariable Long id){return service.get(id);} @GetMapping("/history") Page<StrategicEnterpriseBrainResponse> history(@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC) Pageable p){return service.history(p);}
 @GetMapping("/search") Page<StrategicEnterpriseBrainResponse> search(@RequestParam(required=false)String keyword,@RequestParam(required=false)StrategicEnterpriseBrainPriority priority,@RequestParam(required=false)StrategicEnterpriseBrainStatus status,@PageableDefault(size=20,sort="createdAt",direction=Sort.Direction.DESC)Pageable p){return service.search(keyword,priority,status,p);}
 @PostMapping("/{id}/review") StrategicEnterpriseBrainResponse review(@PathVariable Long id,@Valid @RequestBody StrategicEnterpriseBrainActionRequest q){return service.review(id,q);} @PostMapping("/{id}/approve") StrategicEnterpriseBrainResponse approve(@PathVariable Long id,@Valid @RequestBody StrategicEnterpriseBrainActionRequest q){return service.approve(id,q);} @PostMapping("/{id}/reject") StrategicEnterpriseBrainResponse reject(@PathVariable Long id,@Valid @RequestBody StrategicEnterpriseBrainActionRequest q){return service.reject(id,q);} @PostMapping("/{id}/publish") StrategicEnterpriseBrainResponse publish(@PathVariable Long id,@Valid @RequestBody StrategicEnterpriseBrainActionRequest q){return service.publish(id,q);}
 @GetMapping({"/analytics","/dashboard"}) StrategicEnterpriseBrainAnalyticsResponse analytics(){return service.analytics();} @GetMapping("/health") Map<String,String> health(){return Map.of("status","UP","mode","NEXUSONE_AI_STRATEGIC_AUTONOMOUS_ENTERPRISE_BRAIN");}
}