package ai.nexusone.entity;
import ai.nexusone.enums.*; import jakarta.persistence.*; import java.time.LocalDateTime;
@Entity @Table(name="knowledge_experience_records",indexes={@Index(name="idx_knowledge_category",columnList="category"),@Index(name="idx_knowledge_status",columnList="status"),@Index(name="idx_knowledge_created",columnList="createdAt")})
public class KnowledgeExperienceRecord {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Column(nullable=false) private String title; @Enumerated(EnumType.STRING) @Column(nullable=false) private KnowledgeCategory category;
 @Column(nullable=false) private String sourceModule; private Long incidentId,decisionId,executionId,outcomeId,learningId;
 @Column(length=2000,nullable=false) private String businessContext; @Column(length=2000,nullable=false) private String problemStatement;
 @Column(length=2000,nullable=false) private String solutionSummary; @Column(length=2500,nullable=false) private String lessonsLearned;
 @Column(length=2500,nullable=false) private String bestPractices; @Column(length=4000,nullable=false) private String reusablePlaybook;
 @Column(nullable=false) private Double confidenceScore; @Column(nullable=false) private Integer reuseCount=0;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private KnowledgeStatus status=KnowledgeStatus.DRAFT;
 @Column(nullable=false) private String createdBy; private String validatedBy; private LocalDateTime validatedAt,createdAt,updatedAt;
 @PrePersist void insert(){createdAt=updatedAt=LocalDateTime.now();if(reuseCount==null)reuseCount=0;if(status==null)status=KnowledgeStatus.DRAFT;} @PreUpdate void update(){updatedAt=LocalDateTime.now();}
 public Long getId(){return id;} public String getTitle(){return title;} public void setTitle(String v){title=v;} public KnowledgeCategory getCategory(){return category;} public void setCategory(KnowledgeCategory v){category=v;} public String getSourceModule(){return sourceModule;} public void setSourceModule(String v){sourceModule=v;}
 public Long getIncidentId(){return incidentId;} public void setIncidentId(Long v){incidentId=v;} public Long getDecisionId(){return decisionId;} public void setDecisionId(Long v){decisionId=v;} public Long getExecutionId(){return executionId;} public void setExecutionId(Long v){executionId=v;} public Long getOutcomeId(){return outcomeId;} public void setOutcomeId(Long v){outcomeId=v;} public Long getLearningId(){return learningId;} public void setLearningId(Long v){learningId=v;}
 public String getBusinessContext(){return businessContext;} public void setBusinessContext(String v){businessContext=v;} public String getProblemStatement(){return problemStatement;} public void setProblemStatement(String v){problemStatement=v;} public String getSolutionSummary(){return solutionSummary;} public void setSolutionSummary(String v){solutionSummary=v;} public String getLessonsLearned(){return lessonsLearned;} public void setLessonsLearned(String v){lessonsLearned=v;} public String getBestPractices(){return bestPractices;} public void setBestPractices(String v){bestPractices=v;} public String getReusablePlaybook(){return reusablePlaybook;} public void setReusablePlaybook(String v){reusablePlaybook=v;}
 public Double getConfidenceScore(){return confidenceScore;} public void setConfidenceScore(Double v){confidenceScore=v;} public Integer getReuseCount(){return reuseCount;} public void setReuseCount(Integer v){reuseCount=v;} public KnowledgeStatus getStatus(){return status;} public void setStatus(KnowledgeStatus v){status=v;} public String getCreatedBy(){return createdBy;} public void setCreatedBy(String v){createdBy=v;} public String getValidatedBy(){return validatedBy;} public void setValidatedBy(String v){validatedBy=v;} public LocalDateTime getValidatedAt(){return validatedAt;} public void setValidatedAt(LocalDateTime v){validatedAt=v;} public LocalDateTime getCreatedAt(){return createdAt;} public LocalDateTime getUpdatedAt(){return updatedAt;}
}
